Repository Joystream/pioneer, pull requests merged in 2022-11, with the labels that each got.

#3713 Fix/filter lead
  packages/ui/src/working-groups/components/ApplicantsList.tsx
  packages/ui/src/working-groups/components/Worker.tsx
  packages/ui/src/working-groups/components/WorkersList.tsx
Labels: community-dev, jsg-code-review, waiting-for-checks

#3739 Withdraw candidacy tooltip (#2507)
  packages/ui/src/council/modals/WithdrawCandidacyModal/WithdrawWarningModal.tsx
  packages/ui/test/council/modals/WithdrawCandidacyModal.test.tsx
Labels: community-dev, jsg-code-review

#3791 Allow to withdraw stake of rejected applications (#3251)
  packages/ui/src/working-groups/components/ApplicationsList.tsx
Labels: community-dev, jsg-code-review

#3778 Hide rationale from Slash and Decrease WGL stake details (#3458)
  packages/ui/src/working-groups/components/Activities/ActivitiesModals/StakeChanged/StakeChangedModal.tsx
  packages/ui/src/working-groups/components/Activities/StakeSlashedContent.tsx
Labels: community-dev, jsg-code-review

#3755 Tooltips on `TriggerAndDiscussionStep` (#2346)
  packages/ui/src/proposals/modals/AddNewProposal/components/TriggerAndDiscussionStep.tsx
Labels: community-dev, jsg-code-review

#3746 Add handle / name tooltips on `BuyMembershipFormModal` (#3024)
  packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
Labels: community-dev, jsg-code-review

#3774 Show default target of WG Openings as 1 (#2539)
  packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
  packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningDetails.tsx
  packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningListItem.tsx
Labels: community-dev, jsg-code-review

#3784 🪠 Resubscribe to QN state to validate tx
  packages/ui/src/app/components/ConnectionStatusDot.tsx
  packages/ui/src/common/hooks/useBlockHash.ts
  packages/ui/src/common/hooks/useQueryNodeTransactionStatus.ts
  packages/ui/src/common/hooks/useSignAndSendTransaction.ts
  packages/ui/test/common/components/ConnectionStatusDot.test.tsx
Labels: skip-asana-sync, carthage

#3785 🚧 Parse the value of `REACT_APP_IS_UNDER_MAINTENANCE`
  packages/ui/src/app/App.tsx
  packages/ui/src/common/utils/env.ts
Labels: skip-asana-sync, carthage

#3795 ⏳ Fix the recovery time of the voting and candidacy locks
  packages/ui/src/accounts/components/AccountItem/components/lockItems/CouncilCandidateLockItem.tsx
  packages/ui/src/accounts/components/AccountItem/components/lockItems/VoteLockItem.tsx
  packages/ui/src/council/hooks/useCouncilRemainingPeriod.ts
  packages/ui/src/council/hooks/useElectionStage.ts
Labels: skip-asana-sync, carthage

#3712 🖲️ Fix on forum update transactions progress
  packages/ui/src/forum/components/PostList/PostEditor.tsx
  packages/ui/src/forum/components/Thread/ThreadTitle.tsx
  packages/ui/src/forum/components/threads/ThreadListItem.tsx
  packages/ui/src/forum/modals/EditThreadTitleModal/EditThreadTitleModal.tsx
  packages/ui/src/forum/modals/EditThreadTitleModal/machine.ts
Labels: waiting-for-checks

#3789 Fix rejected application status on `ApplicationsList` (#2913)
  packages/ui/src/working-groups/components/ApplicationsList.tsx
Labels: community-dev, jsg-code-review

#3710 FIX - Past Proposals: Remember last search #2915
  packages/ui/src/app/pages/Proposals/PastProposals.tsx
  packages/ui/src/proposals/components/ProposalFilters/ProposalFilters.tsx
Labels: community-dev, jsg-code-review

#3825 😤 Fix voting lock recovery again
  packages/ui/dev/node-mocks/commands/council/announce.ts
  packages/ui/dev/node-mocks/commands/council/vote.ts
  packages/ui/src/accounts/components/AccountItem/components/lockItems/CouncilorLockItem.tsx
  packages/ui/src/accounts/hooks/useGroupLocks/helpers.ts
  packages/ui/src/council/hooks/useCouncilRemainingPeriod.ts
  packages/ui/src/council/hooks/useElectionStage.ts
  packages/ui/src/council/hooks/useLatestElection.ts
Labels: qa-task, carthage

#3749 Fix translation (#2648)
  packages/ui/src/services/i18n/dict/ru/bounty.json
Labels: low-prio, community-dev, jsg-code-review

#3757 Sort members (#2334)
  packages/ui/src/memberships/modals/SwitchMemberModal/SwitchMemberModal.tsx
Labels: community-dev, jsg-code-review, waiting-for-checks

#3839 🚑️ Fix the faucet CAPTCHA
  packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
Labels: carthage

#3827 🔖 Set Pioneer the version to `0.1.0`
  docs/README.md
  docs/mocks.md
  package.json
  packages/markdown-editor/package.json
  packages/ui/package.json
Labels: carthage

#3773 Update Sidebar membership display after edit tx (#3133)
  packages/ui/src/memberships/modals/UpdateMembershipModal/UpdateMembershipModal.tsx
Labels: community-dev, jsg-code-review

#3766 Stake tooltip on announce candidacy signing modal (#3670)
  packages/ui/src/council/modals/AnnounceCandidacy/AnnounceCandidacyModal.tsx
  packages/ui/src/council/modals/RestoreVotes/RestoreVotesModal.tsx
Labels: community-dev, jsg-code-review

#3793 Ease validation for `minContext` and `maxContext` (#2601)
  packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
Labels: community-dev, jsg-code-review, waiting-for-checks

#3814 📮 Fix Show Election button on Vote lock
  packages/ui/src/accounts/components/AccountItem/components/lockItems/VoteLockItem.tsx
  packages/ui/src/council/queries/__generated__/council.generated.tsx
  packages/ui/src/council/queries/council.graphql
Labels: waiting-for-checks

#3809 Membership handle validation (#3263)
  packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
Labels: community-dev, jsg-code-review

#3866 VoteForCouncil: Fix use total balance
  packages/ui/src/accounts/components/SelectAccount/SelectAccount.tsx
Labels: community-dev, jsg-code-review

#3797 Votes backup CTA on `VoteForCouncilSuccessModal` (#1633)
  packages/ui/src/council/modals/VoteForCouncil/VoteForCouncilSuccessModal.tsx
  packages/ui/test/council/pages/Election.test.tsx
  packages/ui/test/setup.ts
Labels: high-prio, community-dev, jsg-code-review

#3881 🩹 Temp fix for the revealing stage
  packages/ui/src/council/hooks/useElectionVotes.ts
Labels: hot-fix

#3775 Refactor tooltip links (#3743)
  packages/ui/src/accounts/components/StakeStep.tsx
  packages/ui/src/app/pages/Election/Election.tsx
  packages/ui/src/app/pages/Profile/MyAccounts.tsx
  packages/ui/src/app/pages/WorkingGroups/WorkingGroup/OpeningsTab.tsx
  packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
  packages/ui/src/bounty/modals/AddBountyModal/components/FundingDetailsStep.tsx
  packages/ui/src/bounty/modals/ContributeFundsModal/ContributeFundsModal.tsx
  packages/ui/src/bounty/modals/SubmitJudgementModal/components/WinnersSelection.tsx
  packages/ui/src/common/components/Tooltip/Tooltip.tsx
  packages/ui/src/common/components/forms/InputComponent.tsx
  packages/ui/src/common/components/icons/symbols/LinkSymbol.tsx
  packages/ui/src/council/components/pastCouncil/PastCouncilStats.tsx
  packages/ui/src/forum/components/threads/ThreadListItem.tsx
  packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
  packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipSignModal.tsx
  packages/ui/src/memberships/modals/InviteMemberModal/InviteMemberFormModal.tsx
  packages/ui/src/proposals/components/ProposalList/ProposalListItem.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SetReferralCut.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/CreateWorkingGroupLeadOpening/StakingPolicyAndReward.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/StakingAccountStep.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/TriggerAndDiscussionStep.tsx
  packages/ui/src/working-groups/components/ApplicantsList.tsx
  packages/ui/src/working-groups/components/Worker.tsx
Labels: community-dev, jsg-code-review
