Repository Joystream/pioneer, pull requests merged in 2022-06, with the labels that each got.

#3128 Exclude moderated threads from my threads, latest threads and watchlisted threads.
  packages/ui/src/forum/hooks/useLatestForumThreads.ts
  packages/ui/src/forum/hooks/useMyThreads.ts
  packages/ui/src/forum/hooks/useWatchlistedThreads.ts
Labels: community-dev, jsg-code-review

#3129 Strip backslashes in MarkdownPreview to make it work
  packages/ui/src/common/components/MarkdownPreview/MarkdownPreview.tsx
Labels: community-dev, jsg-code-review

#3101 Fix invalid stake on WG opening page
  packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
Labels: community-dev, jsg-code-review

#3126 Add proposal ID to proposal card (#2296)
  packages/ui/src/app/pages/Proposals/ProposalPreview.tsx
  packages/ui/src/common/components/buttons/CopyButton.tsx
  packages/ui/src/proposals/components/ProposalList/ProposalList.tsx
  packages/ui/src/proposals/components/ProposalList/ProposalListItem.tsx
  packages/ui/src/proposals/constants/styles.ts
Labels: community-dev, jsg-code-review

#3192 💥 Fix past councils WG page crash
  packages/ui/src/council/types/PastCouncil.ts
  packages/ui/src/council/types/PastCouncilWorkingGroup.ts
Labels: hot-fix

#3194 🖇️ Add links to FM banner
  packages/ui/src/app/components/FMBanner.tsx
  packages/ui/src/common/components/icons/USFlag.tsx
Labels: hot-fix

#3173 Fix/Top threads tab is not clickable on forum
  packages/ui/src/app/pages/Forum/ForumModule.tsx
  packages/ui/src/app/pages/Forum/TopThreads.tsx
  packages/ui/src/forum/hooks/useTopForumThreads.ts
Labels: jsg-code-review

#3178 Markdown Support: Use RemarkGFM to support additional syntax.
  packages/ui/package.json
  packages/ui/src/common/components/MarkdownPreview/MarkdownPreview.tsx
  packages/ui/src/common/components/MarkdownPreview/MarkdownPreviewStyles.tsx
  yarn.lock
Labels: jsg-code-review

#3113 🩹 Improving UX at page refresh
  packages/ui/src/app/GlobalModals.tsx
  packages/ui/src/common/components/buttons/DetailsButton.stories.tsx
  packages/ui/src/common/components/buttons/DetailsButton.tsx
  packages/ui/src/common/components/page/Sidebar/LinksIcons/SignOutIcon.tsx
  packages/ui/src/memberships/components/Avatar.tsx
  packages/ui/src/memberships/components/components.tsx
  packages/ui/src/memberships/modals/SignOutModal/SignOutModal.tsx
  packages/ui/src/memberships/modals/SignOutModal/index.ts
  packages/ui/src/memberships/modals/SignOutModal/types.ts
  packages/ui/src/memberships/modals/SwitchMemberModal/SwitchMemberModal.tsx
  packages/ui/src/memberships/providers/membership/provider.tsx
  packages/ui/test/membership/components/CurrentMember.test.tsx
Labels: hot-fix

#3250 #3025 Update medium modal padding to better fit on smaller screens.
  packages/ui/src/common/components/Modal/Modal.tsx
Labels: jsg-code-review

#3252 #2220 Put onClick={toggleOpen} to the whole Toggle component.
  packages/ui/src/common/components/buttons/Toggle.tsx
  packages/ui/src/memberships/components/MemberProfile/MemberRoleToggle.tsx
Labels: community-dev, jsg-code-review

#3249 Add prev step button on ApplyForRoleModal (#2445)
  packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.tsx
  packages/ui/src/working-groups/modals/ApplyForRoleModal/machine.ts
Labels: community-dev, jsg-code-review

#3282 ✍️ Fix the post editing feature
  packages/ui/src/common/components/CKEditor/CKEditorStylesOverrides.tsx
Labels: hot-fix
