Repository Joystream/pioneer, pull requests merged in 2022-12, with the labels that each got.

#3758 👾 Sort proposal discussion by block (#3236)
  packages/ui/src/proposals/components/ProposalDiscussions.tsx
Labels: community-dev, jsg-code-review, waiting-for-checks

#3931 Hide empty `Moderators` (#3922)
  packages/ui/src/app/pages/Forum/ForumCategory.tsx
  packages/ui/src/forum/components/category/ForumMain.tsx
Labels: community-dev, jsg-code-review

#3841 Wording on `MoveFundsModal` (#3835)
  packages/ui/src/accounts/modals/MoveFoundsModal/MoveFundsModal.tsx
Labels: community-dev, jsg-code-review

#3921 Total recoverable balance (#2847)
  packages/ui/src/app/pages/Profile/MyAccounts.tsx
Labels: community-dev, jsg-code-review

#3709 feat: add external links for WGs
  packages/ui/src/common/helpers.ts
  packages/ui/src/working-groups/components/WorkingGroupListItem.tsx
Labels: community-dev, jsg-code-review

#3941 Eliminate tJOY
  packages/ui/src/services/i18n/dict/en/accounts.json
  packages/ui/src/services/i18n/dict/en/bounty.json
  packages/ui/src/services/i18n/dict/en/common.json
  packages/ui/src/services/i18n/dict/ru/bounty.json
Labels: community-dev, jsg-code-review

#3790 Show sum of my vote stakes on `CandidateVote` (#2985)
  packages/ui/src/council/components/election/CandidateVote/CandidateVote.stories.tsx
  packages/ui/src/council/components/election/CandidateVote/CandidateVote.tsx
  packages/ui/src/council/components/election/CandidateVote/RevealingStageVotes.tsx
  packages/ui/src/council/components/election/pastElection/PastElectionTabs.tsx
  packages/ui/src/council/components/election/revealing/RevealingStage.tsx
  packages/ui/src/council/hooks/useMyCastVotes.ts
  packages/ui/test/council/components/ElectionVotes.test.tsx
Labels: community-dev, jsg-code-review

#3842 Hide error while loading on `ClaimVestingModal` (#3838)
  packages/ui/src/accounts/modals/ClaimVestingModal/ClaimVestingModal.tsx
Labels: community-dev, jsg-code-review

#3860 hiringLimit 0 to 1 (#2451)
  packages/ui/src/working-groups/types/WorkingGroupOpening.ts
Labels: community-dev, jsg-code-review

#3796 Don't overwrite watchlist (#3769)
  packages/ui/src/forum/components/Thread/WatchlistButton.tsx
Labels: community-dev, jsg-code-review

#3925 added description for ForumPageHeader (#3904)
  packages/ui/src/app/pages/Forum/ForumCategory.tsx
  packages/ui/src/forum/components/ForumPageHeader.tsx
Labels: community-dev, jsg-code-review

#3952 Forum refetch fix (#3915)
  packages/ui/src/forum/components/category/LatestPost.tsx
  packages/ui/src/forum/components/category/PopularThread.tsx
Labels: community-dev, jsg-code-review

#3826 Stake changed Activities (#3458)
  packages/ui/src/working-groups/components/Activities/ActivitiesModals/StakeChanged/StakeChangedModal.tsx
  packages/ui/src/working-groups/components/Activities/StakeSlashedContent.tsx
  packages/ui/src/working-groups/types/WorkingGroupActivity/types.ts
Labels: community-dev, jsg-code-review

#3756 Display whitelisted members for closed proposal discussions (#2480)
  packages/ui/src/proposals/components/ProposalDiscussions.tsx
  packages/ui/test/proposals/components/ProposalDiscussion.test.tsx
Labels: community-dev, jsg-code-review

#3893 thread datetime
  packages/ui/src/app/pages/Forum/ForumThread.tsx
  packages/ui/src/common/helpers.ts
Labels: community-dev, jsg-code-review

#3923 Update `Withdraw Candidacy` warning (#3895)
  packages/ui/src/council/modals/WithdrawCandidacyModal/WithdrawWarningModal.tsx
  packages/ui/test/council/modals/WithdrawCandidacyModal.test.tsx
Labels: community-dev, jsg-code-review

#3926 Show new invitation quota on `ProposalDetails` (#3902)
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SetMembershipLeadInvitationQuota.tsx
  packages/ui/src/proposals/modals/AddNewProposal/getSpecificParameters.ts
  packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
  packages/ui/src/proposals/queries/__generated__/proposals.generated.tsx
  packages/ui/src/proposals/queries/proposals.graphql
  packages/ui/src/proposals/types/ProposalDetails.ts
Labels: community-dev, jsg-code-review

#3927 Hide `Earned in 24h` until calculation fix (#3181)
  packages/ui/src/memberships/components/MemberProfile/MemberRoleToggle.tsx
  packages/ui/src/working-groups/hooks/useWorkerEarnings.ts
Labels: community-dev, jsg-code-review

#3987 Settings: Chain info formatting + i18n (#2342)
  packages/ui/src/app/pages/Settings/Settings.tsx
  packages/ui/src/services/i18n/dict/en/settings.json
Labels: community-dev, jsg-code-review

#3981 Fixed back link issue on opening with empty referrer
  packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
  packages/ui/src/common/components/page/PreviousPage.tsx
Labels: community-dev, jsg-code-review

#3982 Fixed stake not displayed
  packages/ui/src/council/modals/AnnounceCandidacy/AnnounceCandidacyModal.tsx
Labels: community-dev, jsg-code-review

#3878 Add InvitationLock tooltip on My Accounts (#3479)
  packages/ui/src/accounts/components/AccountItem/components/lockItems/InvitationLockItem.tsx
Labels: community-dev, jsg-code-review

#3975 Fix initial 'member.about' on `UpdateMembershipFormModal` (#3973)
  packages/ui/src/memberships/modals/UpdateMembershipModal/UpdateMembershipFormModal.tsx
Labels: community-dev, jsg-code-review

#3976 Empty videoHints for now (#3971)
  packages/ui/src/common/constants/videoHints.ts
Labels: community-dev, jsg-code-review

#3964 Hide Languages tab (#3955)
  packages/ui/src/app/pages/Settings/Settings.tsx
Labels: community-dev, jsg-code-review

#3932 the replies counter is not working properly (#3912)
  packages/ui/src/forum/components/threads/ThreadListItem.tsx
Labels: community-dev, jsg-code-review

#3945 `StakeStep` tooltip (#3944)
  packages/ui/src/council/modals/AnnounceCandidacy/components/StakeStep.tsx
Labels: community-dev, jsg-code-review

#3741 Restore `Use Max` button on `TransferFormModal` (#1816)
  packages/ui/src/accounts/hooks/useTransactionFee.ts
  packages/ui/src/accounts/modals/TransferModal/TransferFormModal.tsx
  packages/ui/src/accounts/modals/TransferModal/TransferModal.tsx
  packages/ui/src/accounts/modals/TransferModal/machine.ts
  packages/ui/src/app/constants/currency.ts
  packages/ui/src/common/constants/numbers.ts
  packages/ui/src/common/providers/transactionFees/context.ts
Labels: community-dev, jsg-code-review

#3754 Fix/add tooltip issue 3682
  packages/ui/src/council/components/election/CandidateVote/CandidateVote.tsx
  packages/ui/test/council/components/ElectionVotes.test.tsx
  packages/ui/test/council/pages/PastElection.test.tsx
Labels: community-dev, jsg-code-review

#3906 🤑 Channel payouts proposal
  .yarn/patches/@joystream-js-npm-1.0.0-b6846bd440.patch
  package.json
  packages/ui/jest.config.js
  packages/ui/package.json
  packages/ui/src/common/components/FileDropzone/FileDropzone.tsx
  packages/ui/src/common/components/FileDropzone/helpers.ts
  packages/ui/src/common/utils/validation.tsx
  packages/ui/src/proposals/hooks/useProposalConstants.ts
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/ChannelIncentivesPayout/ChannelIncentivesPayout.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/ChannelIncentivesPayout/helpers.ts
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/RuntimeUpgrade.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SpecificParametersStep.tsx
  packages/ui/src/proposals/modals/AddNewProposal/getSpecificParameters.ts
  packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
  packages/ui/src/proposals/modals/AddNewProposal/machine.ts
  packages/ui/src/proposals/model/proposalDescriptions.ts
  packages/ui/src/proposals/model/proposalDetails.ts
  packages/ui/src/proposals/types/proposals.ts
  packages/ui/test/setup.ts
  yarn.lock
Labels: ephesus

#3728 Add opening title to reward notification (#3342)
  packages/ui/src/working-groups/components/Activities/WorkerRewardAmountUpdatedContent.tsx
  packages/ui/src/working-groups/hooks/useGroupActivities.ts
  packages/ui/src/working-groups/queries/__generated__/workingGroupsEvents.generated.tsx
  packages/ui/src/working-groups/queries/workingGroupsEvents.graphql
  packages/ui/src/working-groups/types/WorkingGroupActivity/casts.ts
  packages/ui/src/working-groups/types/WorkingGroupActivity/types.ts
Labels: community-dev, jsg-code-review

#3815 Fix: Handle empty vesting balances (My Accounts)
  packages/ui/src/accounts/components/AccountItem/AccountItem.tsx
  packages/ui/src/accounts/components/AccountLocks.tsx
  packages/ui/src/accounts/hooks/useMyTotalBalances.ts
  packages/ui/src/app/components/SideBar.tsx
  packages/ui/src/common/components/icons/locks/AppsWorkerIcon.tsx
  packages/ui/src/common/components/icons/locks/index.ts
  packages/ui/src/common/components/page/Sidebar/LinksIcons/AppsIcon.tsx
  packages/ui/src/common/components/page/Sidebar/LinksIcons/index.ts
  packages/ui/src/common/utils.ts
  packages/ui/src/common/utils/bn.ts
  packages/ui/src/working-groups/components/WorkingGroupImage.stories.tsx
Labels: community-dev, jsg-code-review, has-conflicts
