Repository Joystream/pioneer, pull requests merged in 2022-07, with the labels that each got.

#3325 #2705 empty upcoming openings section
  packages/ui/src/app/pages/WorkingGroups/WorkingGroup/OpeningsTab.tsx
Labels: jsg-code-review

#3322 Fix bounties modals not resizing with windows size
  packages/ui/src/common/components/Modal/Modal.tsx
Labels: community-dev, jsg-code-review

#3317 👨‍🚀 Filter withdrawn applications from openings
  packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
Labels: community-dev, jsg-code-review

#3357 🚅 Implementing candidate bullet points
  packages/ui/src/council/modals/VoteForCouncil/components/CandidacyReview.tsx
Labels: community-dev

#3367 🖌️ Fix extra "padding" in modals
  packages/ui/src/common/components/Modal/Modal.tsx
Labels: community-dev

#3359 🐻‍❄️ Polling on chosen pages
  packages/ui/src/app/pages/Council/Council.tsx
  packages/ui/src/app/pages/Election/Election.tsx
  packages/ui/src/app/pages/Forum/ForumCategories.tsx
  packages/ui/src/app/pages/Proposals/PastProposals.tsx
  packages/ui/src/app/pages/Proposals/Proposals.tsx
  packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpenings.tsx
  packages/ui/src/common/hooks/useRefetchQueries.ts
  packages/ui/src/proposals/components/ProposalList/ProposalList.tsx
  packages/ui/test/council/pages/Council.test.tsx
Labels: release:stabilisation9

#3327 💸 Multiple wallets support
  packages/ui/package.json
  packages/ui/src/accounts/components/AccountInfo.tsx
  packages/ui/src/accounts/hooks/useTransactionFee.ts
  packages/ui/src/accounts/providers/accounts/provider.tsx
  packages/ui/src/accounts/types/accounts.ts
  packages/ui/src/app/App.tsx
  packages/ui/src/app/GlobalModals.tsx
  packages/ui/src/app/assets/images/OnBoarding/accountImage.png
  packages/ui/src/app/components/ExtensionWarning.tsx
  packages/ui/src/app/components/OnboardingOverlay/OnBoardingOverlay.tsx
  packages/ui/src/app/components/OnboardingOverlay/components/BenefitListItem.tsx
  packages/ui/src/app/components/OnboardingOverlay/components/BenefitsTable.tsx
  packages/ui/src/app/components/OnboardingOverlay/components/DrawerContainer.tsx
  packages/ui/src/common/components/Modal/Modal.tsx
  packages/ui/src/common/components/Stepper/HorizontalStepper.tsx
  packages/ui/src/common/components/Stepper/Stepper.tsx
  packages/ui/src/common/components/Stepper/VerticalStaticStepper.stories.tsx
  packages/ui/src/common/components/Stepper/VerticalStaticStepper.tsx
  packages/ui/src/common/components/TransactionStatus/TransactionStatus.tsx
  packages/ui/src/common/components/buttons/DetailsButton.tsx
  packages/ui/src/common/components/page/Sidebar/LinksIcons/DisconnectWalletIcon.tsx
  packages/ui/src/common/hooks/useProcessTransaction.ts
  packages/ui/src/common/modals/OnBoardingModal/OnBoardingAccount.tsx
  packages/ui/src/common/modals/OnBoardingModal/OnBoardingModal.tsx
  packages/ui/src/common/modals/OnBoardingModal/OnBoardingPlugin.tsx
  packages/ui/src/common/modals/OnBoardingModal/components/ConnectAccountItem.tsx
  packages/ui/src/common/modals/OnBoardingModal/components/ConnectWalletItem.tsx
  packages/ui/src/common/modals/OnBoardingModal/components/NoAccountStep.tsx
  packages/ui/src/common/modals/OnBoardingModal/components/SelectAccountStep.tsx
  packages/ui/src/common/providers/onboarding/provider.tsx
  packages/ui/src/memberships/components/CurrentMember/CurrentMember.tsx
  packages/ui/src/memberships/modals/DisconnectWalletModal/DisconnectWalletModal.tsx
  packages/ui/src/memberships/modals/DisconnectWalletModal/index.ts
  packages/ui/src/memberships/modals/DisconnectWalletModal/types.ts
  packages/ui/src/memberships/modals/SwitchMemberModal/SwitchMemberModal.tsx
  packages/ui/src/memberships/providers/membership/provider.tsx
  packages/ui/test/app/OnBoardingOverlay.test.tsx
  packages/ui/test/common/components/TransactionButton.test.tsx
  packages/ui/test/common/hooks/useOnBoarding.test.tsx
  packages/ui/test/common/modals/OnBoardingModal.test.tsx
  packages/ui/test/forum/modals/CreateThreadModal.test.tsx
  packages/ui/test/membership/components/CurrentMember.test.tsx
  yarn.lock
Labels: release:stabilisation9

#3372 🆕 New graphql schema for carthage
  packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
  packages/ui/src/common/api/schemas/schema.graphql
  packages/ui/src/council/queries/__generated__/council.generated.tsx
  packages/ui/src/council/queries/__generated__/councilEvents.generated.tsx
  packages/ui/src/forum/queries/__generated__/forumEvents.generated.tsx
  packages/ui/src/proposals/queries/__generated__/proposals.generated.tsx
  packages/ui/src/proposals/queries/__generated__/proposalsEvents.generated.tsx
  packages/ui/src/working-groups/queries/__generated__/workingGroupsEvents.generated.tsx
  packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
Labels: carthage

#3374 ✉️ Work with Joystream address format
  packages/ui/src/accounts/providers/accounts/provider.tsx
Labels: carthage

#3338 Fix Candidates Card "Staked" copy
  packages/ui/src/council/components/election/CandidateCard/CandidateCard.tsx
  packages/ui/test/council/pages/Election.test.tsx
Labels: community-dev, jsg-code-review, waiting-for-checks

#3384 🪲 Fix carthage `ProxyApi` related bugs
  packages/ui/src/proxyApi/models/payload.ts
Labels: carthage

#3315 🍡 Feature/new token calculation
  packages/ui/src/bounty/modals/SubmitJudgementModal/components/WinnersSelection.tsx
  packages/ui/src/bounty/modals/WithdrawSignModal/WithdrawSignModal.tsx
  packages/ui/src/bounty/modals/WithdrawWorkEntryModal/WithdrawWorkEntryModal.tsx
  packages/ui/src/common/components/statistics/StakeStat.tsx
  packages/ui/src/common/components/statistics/TokenValueStat.tsx
  packages/ui/src/common/components/typography/TokenValue.stories.tsx
  packages/ui/src/common/components/typography/TokenValue.tsx
  packages/ui/src/common/constants/numbers.ts
  packages/ui/src/common/model/formatters.ts
  packages/ui/src/common/utils/bn.ts
  packages/ui/src/memberships/components/MemberProfile/MemberRoleToggle.tsx
  packages/ui/src/working-groups/components/Roles/RolesList.tsx
  packages/ui/src/working-groups/hooks/useWorkerEarnings.ts
  packages/ui/test/common/model/formatters.test.ts
  packages/ui/test/setup.ts
  packages/ui/test/working-groups/components/WorkingGroupListItem.test.tsx
Labels: carthage

#3391 🔒 Unlocking Gateway WG
  packages/ui/src/app/pages/WorkingGroups/WorkingGroups.tsx
  packages/ui/src/common/helpers.ts
  packages/ui/src/working-groups/components/SelectWorkingGroup/OptionsListWorkingGroup.tsx
  packages/ui/src/working-groups/components/WorkingGroupListItem.tsx
  packages/ui/src/working-groups/model/workingGroupName.ts
Labels: carthage

#3395 ♾️ Fix for infinite waiting modal
  packages/ui/src/common/providers/transactionFees/provider.tsx
Labels: carthage

#3393 📨 New input logic
  packages/ui/package.json
  packages/ui/src/accounts/components/StakeStep.tsx
  packages/ui/src/accounts/modals/TransferModal/TransferFormModal.tsx
  packages/ui/src/bounty/modals/AddBountyModal/components/FundingDetailsStep.tsx
  packages/ui/src/bounty/modals/AddBountyModal/components/JudgingDetailsStep.tsx
  packages/ui/src/bounty/modals/AddBountyModal/components/WorkingDetailsStep.tsx
  packages/ui/src/bounty/modals/AnnounceWorkEntryModal/AnnounceWorkEntryModal.tsx
  packages/ui/src/bounty/modals/ContributeFundsModal/ContributeFundsModal.tsx
  packages/ui/src/bounty/modals/SubmitJudgementModal/SubmitJudgementModal.tsx
  packages/ui/src/bounty/modals/SubmitJudgementModal/components/WinnersSelection.tsx
  packages/ui/src/bounty/modals/SubmitJudgementModal/machine.ts
  packages/ui/src/common/components/OpeningDuration/OpeningDuration.tsx
  packages/ui/src/common/components/forms/InputComponent.stories.tsx
  packages/ui/src/common/components/forms/InputComponent.tsx
  packages/ui/src/common/components/forms/InputNumber.tsx
  packages/ui/src/common/components/forms/TokenInput.tsx
  packages/ui/src/common/components/forms/index.tsx
  packages/ui/src/common/components/typography/TokenValue.tsx
  packages/ui/src/common/model/formatters.ts
  packages/ui/src/common/utils/bn.ts
  packages/ui/src/council/modals/AnnounceCandidacy/components/StakeStep.tsx
  packages/ui/src/memberships/modals/TransferInviteModal/TransferInviteFormModal.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/DecreaseWorkingGroupLeadStake.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/FundingRequest.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SetCouncilBudgetIncrement.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SetCouncilorReward.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SetInitialInvitationBalance.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SetInitialInvitationCount.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SetMaxValidatorCount.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SetMembershipLeadInvitationQuota.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SetMembershipPrice.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SetReferralCut.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SetWorkingGroupLeadReward.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SlashWorkingGroupLead.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/TerminateWorkingGroupLead.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/UpdateWorkingGroupBudget.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/CreateWorkingGroupLeadOpening/StakingPolicyAndReward.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/TriggerAndDiscussionStep.tsx
  packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
  packages/ui/src/proposals/modals/AddNewProposal/machine.ts
  packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.tsx
  packages/ui/src/working-groups/modals/ApplyForRoleModal/StakeStep.tsx
  packages/ui/src/working-groups/modals/IncreaseWorkerStakeModal/IncreaseWorkerStakeModal.tsx
  packages/ui/src/working-groups/modals/IncreaseWorkerStakeModal/SuccessModal.tsx
  packages/ui/test/accounts/modal/TransferModal.test.tsx
  packages/ui/test/common/model/formatters.test.ts
  packages/ui/test/council/modals/AnnounceCandidacyModal.test.tsx
  packages/ui/test/council/modals/VoteForCouncilModal.test.tsx
  packages/ui/test/membership/modals/TransferInviteModal.test.tsx
  packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
  packages/ui/test/working-groups/modals/IncreaseWorkerStakeModal.test.tsx
  yarn.lock
Labels: carthage
