Repository Joystream/pioneer, pull requests merged in 2022-10, with the labels that each got.

#3681 ✊ Account for abstention in quorum
  packages/ui/src/proposals/components/StatisticsPreview/ProposalStatistics.tsx
Labels: carthage

#3677 🧥 Considering WG name mapping in search
  packages/ui/src/working-groups/components/SelectWorkingGroup/SelectWorkingGroup.tsx
Labels: carthage

#3683 ❌ Fix validation on carthage
  packages/ui/src/common/modals/SignTransactionModal/SignTransactionModal.tsx
  packages/ui/src/council/modals/AnnounceCandidacy/AnnounceCandidacyModal.tsx
Labels: carthage

#3692 🔧 Fix the vote for council modal
  packages/ui/src/council/modals/VoteForCouncil/VoteForCouncilFormModal.tsx
  packages/ui/src/council/modals/VoteForCouncil/VoteForCouncilModal.tsx
Labels: carthage

#3673 fix: Forum first post time display issue
  packages/ui/src/app/pages/Forum/ForumThread.tsx
Labels: community-dev, jsg-code-review

#3680 🧑‍🏭 Maintenance screen
  docs/admin.md
  packages/ui/.env.example
  packages/ui/src/app/App.tsx
  packages/ui/src/app/assets/images/MaintenanceLogo.png
  packages/ui/src/common/components/page/MaintenanceScreen/MaintenanceScreen.stories.tsx
  packages/ui/src/common/components/page/MaintenanceScreen/MaintenanceScreen.tsx
  packages/ui/src/common/constants/styles.ts
  packages/ui/webpack.config.js
Labels: carthage, waiting-for-checks

#3686 👻 Hiding unnecessary loader on proposal list item
  packages/ui/src/proposals/components/ProposalList/ProposalItemVoteDetails.tsx
  packages/ui/test/proposals/components/ProposalListItem.test.tsx
Labels: carthage, waiting-for-checks

#3701 🔥 Hotfix: Allow reusing voting stake in next election
  packages/ui/src/accounts/hooks/useStakingAccountsLocks.ts
Labels: hot-fix

#3708 🪢 Merge main hotfixes into carthage
  packages/ui/src/accounts/hooks/useStakingAccountsLocks.ts
  packages/ui/src/council/components/PastVotes/PastVote/PastVote.tsx
  packages/ui/src/council/types/Election.ts
  packages/ui/src/proposals/modals/VoteForProposal/VoteForProposalModal.tsx
Labels: carthage

#3721 fix: avg stake tooltip typos and link
  packages/ui/src/app/pages/WorkingGroups/WorkingGroup/OpeningsTab.tsx
Labels: jsg-code-review

#3726 fix: tooltips on account creation
  packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
Labels: jsg-code-review

#3732 🎐 Consider withdrawn applications in counters
  packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
  packages/ui/src/overview/queries/__generated__/overview.generated.tsx
  packages/ui/src/working-groups/components/ApplicationsList.tsx
  packages/ui/src/working-groups/queries/__generated__/workingGroups.generated.tsx
  packages/ui/src/working-groups/queries/workingGroups.graphql
  packages/ui/src/working-groups/types/WorkingGroupOpening.ts
Labels: skip-asana-sync, carthage

#3727 Fix WG opening route (#3399)
  packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
  packages/ui/src/working-groups/components/OpeningsList/Opening/OpeningDetails.tsx
  packages/ui/src/working-groups/model/workingGroupName.ts
Labels: jsg-code-review

#3649 Feature stack: Forum - My Thread
  packages/ui/src/app/pages/Forum/ForumArchived.tsx
  packages/ui/src/app/pages/Forum/ForumCategory.tsx
  packages/ui/src/app/pages/Forum/ForumMyThreads.tsx
  packages/ui/src/app/pages/Forum/LatestThreads.tsx
  packages/ui/src/app/pages/Forum/TopThreads.tsx
  packages/ui/src/app/pages/Forum/components/ForumTabs.tsx
  packages/ui/src/forum/components/Thread/ThreadTitle.tsx
  packages/ui/src/forum/components/ThreadCard/ThreadCard.stories.tsx
  packages/ui/src/forum/components/ThreadCard/ThreadCard.tsx
  packages/ui/src/forum/components/threads/LatestActivity.tsx
  packages/ui/src/forum/components/threads/ThreadItem.stories.tsx
  packages/ui/src/forum/components/threads/ThreadList.stories.tsx
  packages/ui/src/forum/components/threads/ThreadList.tsx
  packages/ui/src/forum/components/threads/ThreadListItem.stories.tsx
  packages/ui/src/forum/components/threads/ThreadListItem.tsx
  packages/ui/src/forum/hooks/useMyThreads.ts
  packages/ui/src/forum/modals/DeleteThreadModal/DeleteThreadModal.tsx
  packages/ui/src/forum/modals/EditThreadTitleModal/EditThreadTitleSignModal.tsx
  packages/ui/src/forum/queries/__generated__/forum.generated.tsx
  packages/ui/src/forum/queries/forum.graphql
  packages/ui/src/forum/types/ForumThread.ts
  packages/ui/src/mocks/components/storybook/MockApolloProvider.tsx
  packages/ui/test/forum/modals/DeleteThreadModal.test.tsx
  packages/ui/test/forum/pages/ForumThread.test.tsx
Labels: waiting-for-checks

#3738 Update handbook links and tooltips (#2847)
  packages/ui/src/app/pages/Election/Election.tsx
  packages/ui/src/app/pages/Profile/MyAccounts.tsx
  packages/ui/src/app/pages/WorkingGroups/UpcomingOpening.tsx
  packages/ui/src/app/pages/WorkingGroups/WorkingGroup/AboutTab.tsx
  packages/ui/src/app/pages/WorkingGroups/WorkingGroup/OpeningsTab.tsx
  packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
  packages/ui/src/council/components/pastCouncil/PastCouncilStats.tsx
  packages/ui/src/proposals/components/ProposalList/ProposalListItem.tsx
Labels: community-dev, jsg-code-review

#3760 added tooltip for thread title
  packages/ui/src/forum/components/threads/ThreadListItem.tsx
Labels: community-dev, jsg-code-review

#3740 Invitation lock tooltip (#3479)
  packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipSignModal.tsx
Labels: community-dev, jsg-code-review

#3720 🇩🇬 Rename gateways group
  packages/ui/src/app/components/SideBar.tsx
  packages/ui/src/app/pages/WorkingGroups/WorkingGroups.tsx
  packages/ui/src/common/components/Tooltip/Tooltip.tsx
  packages/ui/src/common/helpers.ts
  packages/ui/src/working-groups/components/WorkingGroupImage.tsx
  packages/ui/src/working-groups/components/WorkingGroupListItem.tsx
  packages/ui/src/working-groups/model/workingGroupName.ts
Labels: skip-asana-sync, carthage

#3635 Forum: cannot search for numbers #3470
  packages/ui/src/common/components/Search/SearchResultsModal.tsx
  packages/ui/src/common/components/forms/FilterBox/FilterSearchBox.tsx
  packages/ui/src/common/hooks/useSearch.ts
Labels: feedback-follow-up, community-dev, jsg-code-review
