Repository Joystream/pioneer, pull requests merged in 2022-08, with the labels that each got.

#3420 Show moderated posts
  packages/ui/src/common/components/icons/AlertRoundedIcon.tsx
  packages/ui/src/common/components/icons/index.ts
  packages/ui/src/forum/components/PostList/ModeratedPost.tsx
  packages/ui/src/forum/components/PostList/PostListItem.stories.tsx
  packages/ui/src/forum/components/PostList/PostListItem.tsx
  packages/ui/src/forum/hooks/useForumThreadPosts.ts
  packages/ui/src/forum/queries/__generated__/forum.generated.tsx
  packages/ui/src/forum/queries/forum.graphql
  packages/ui/src/forum/types/ForumPost.ts
  packages/ui/test/forum/hooks/useForumThreadPosts.test.ts
Labels: community-dev, jsg-code-review

#3455 ⏺️ Fix on TransferInviteModal validation
  packages/ui/src/memberships/modals/TransferInviteModal/TransferInviteFormModal.tsx
Labels: carthage

#3454 🛑 Remove extra tooltip on transaction fee info
  packages/ui/src/common/components/TransactionFee.stories.tsx
  packages/ui/src/common/components/TransactionFee.tsx
Labels: carthage

#3441 🔧 Fixes the wrong group for fill WG opening proposal
  packages/ui/src/proposals/components/ProposalDetails/renderers/Member.tsx
  packages/ui/src/proposals/helpers/getDetailsRenderStructure.ts
  packages/ui/src/proposals/modals/AddNewProposal/getSpecificParameters.ts
Labels: carthage

#3460 🗜️ Introduction of vesting
  packages/ui/src/accounts/components/AccountItem/AccountItem.tsx
  packages/ui/src/accounts/components/AccountItem/components/LockItemWrapper.tsx
  packages/ui/src/accounts/components/AccountItem/components/LocksDetails.tsx
  packages/ui/src/accounts/components/AccountItem/components/VestingLockItem/VestingLockItem.stories.tsx
  packages/ui/src/accounts/components/AccountItem/components/VestingLockItem/VestingLockItem.tsx
  packages/ui/src/accounts/components/AccountItem/components/styles.ts
  packages/ui/src/accounts/components/AccountLocks.tsx
  packages/ui/src/accounts/components/Accounts.tsx
  packages/ui/src/accounts/components/ClaimVestingButton.tsx
  packages/ui/src/accounts/components/SelectAccount/OptionAccount.tsx
  packages/ui/src/accounts/hooks/useMyTotalBalances.ts
  packages/ui/src/accounts/modals/ClaimVestingModal/ClaimVestingModal.stories.tsx
  packages/ui/src/accounts/modals/ClaimVestingModal/ClaimVestingModal.tsx
  packages/ui/src/accounts/modals/ClaimVestingModal/components/SelectVestingAccount.tsx
  packages/ui/src/accounts/modals/ClaimVestingModal/index.ts
  packages/ui/src/accounts/model/BalanceComparator.ts
  packages/ui/src/accounts/model/sortAccounts.ts
  packages/ui/src/accounts/model/toBalances.ts
  packages/ui/src/accounts/types/balances.ts
  packages/ui/src/app/GlobalModals.tsx
  packages/ui/src/app/pages/Profile/MyAccounts.tsx
  packages/ui/src/bounty/modals/AnnounceWorkEntryModal/AnnounceWorkEntryModal.stories.tsx
  packages/ui/src/bounty/modals/CancelBountyModal/BountyCancelModal.stories.tsx
  packages/ui/src/bounty/modals/ContributeFundsModal/ContributeFundsModal.stories.tsx
  packages/ui/src/bounty/modals/SubmitJudgementModal/SubmitJudgementModal.stories.tsx
  packages/ui/src/bounty/modals/SubmitWorkModal/SubmitWorkModal.stories.tsx
  packages/ui/src/bounty/modals/WithdrawContributionModal/WithdrawContributionModal.stories.tsx
  packages/ui/src/bounty/modals/WithdrawWorkEntryModal/WithdrawWorkEntryModal.stories.tsx
  packages/ui/src/bounty/modals/WithdrawalStakeModal/WithdrawStakeModel.stories.tsx
  packages/ui/src/common/components/Modal/Modal.tsx
  packages/ui/src/common/components/icons/locks/VestingLockIcon.tsx
  packages/ui/src/common/components/selects/components.tsx
  packages/ui/src/common/components/statistics/StatisticItem.tsx
  packages/ui/src/common/modals/OnBoardingModal/OnBoardingModal.stories.tsx
  packages/ui/src/common/model/formatters.ts
  packages/ui/src/memberships/modals/SignOutModal/SignOutModal.tsx
  packages/ui/test/_mocks/transactions.ts
  packages/ui/test/accounts/components/MyAccounts.test.tsx
  packages/ui/test/accounts/hooks/useHasRequiredStake.test.tsx
  packages/ui/test/accounts/hooks/useMyTotalBalances.test.tsx
  packages/ui/test/accounts/modal/TransferModal.test.tsx
  packages/ui/test/accounts/model/sortAccounts.test.ts
  packages/ui/test/accounts/model/toBalances.test.ts
  packages/ui/test/bounty/modals/AnnounceWorkEntryModal.test.tsx
  packages/ui/test/bounty/modals/BountyCancelModal.test.tsx
  packages/ui/test/bounty/modals/ContributeFundsModal.test.tsx
  packages/ui/test/bounty/modals/SubmitJudgementModal.test.tsx
  packages/ui/test/bounty/modals/SubmitWorkModal.test.tsx
  packages/ui/test/bounty/modals/WithdrawWorkEntryWork.test.tsx
  packages/ui/test/common/modals/OnBoardingModal.test.tsx
  packages/ui/test/common/model/formatters.test.ts
  packages/ui/test/setup.ts
Labels: waiting-for-checks

#3511 :basecamp: Fix on incorrect base denomination
  packages/ui/src/common/utils/validation.ts
  packages/ui/src/council/modals/AnnounceCandidacy/components/StakeStep.tsx
  packages/ui/src/forum/modals/CreateThreadModal/utils.ts
  packages/ui/src/forum/modals/EditThreadTitleModal/EditThreadTitleSignModal.tsx
  packages/ui/src/memberships/modals/utils.ts
  packages/ui/src/proposals/modals/AddNewProposal/getSpecificParameters.ts
  packages/ui/src/working-groups/modals/ApplyForRoleModal/StakeStep.tsx
  packages/ui/test/forum/modals/CreateThreadModal.test.tsx
Labels: waiting-for-checks

#3506 📨 Fix on invitation lock logic
  packages/ui/src/accounts/modals/MoveFoundsModal/MoveFundsModal.tsx
  packages/ui/src/accounts/modals/MoveFoundsModal/index.ts
  packages/ui/src/common/providers/transactionFees/provider.tsx
  packages/ui/src/council/modals/AnnounceCandidacy/AnnounceCandidacyModal.tsx
  packages/ui/src/council/modals/VoteForCouncil/VoteForCouncilModal.tsx
  packages/ui/src/forum/modals/PostActionModal/CreatePostModal/CreatePostSignModal.tsx
  packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
  packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.tsx
  packages/ui/test/council/modals/AnnounceCandidacyModal.test.tsx
  packages/ui/test/council/modals/VoteForCouncilModal.test.tsx
  packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
  packages/ui/test/working-groups/modals/ApplyForRoleModal.test.tsx
Labels: waiting-for-checks

#3513 🙈 Ignoring validation for undefined constants
  packages/ui/src/common/utils/validation.ts
  packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
Labels: waiting-for-checks

#3193 📄 Signal description copy change
  packages/ui/src/proposals/components/ProposalDetails/renderers/Markdown/components/OpeningDescriptionPreview.tsx
Labels: community-dev

#3574 🧵 Fixed datetime is not displayed for Forum thread
  packages/ui/src/forum/queries/__generated__/forum.generated.tsx
  packages/ui/src/forum/queries/forum.graphql
  packages/ui/src/forum/types/ForumPost.ts
Labels: community-dev, jsg-code-review
