Repository Joystream/pioneer, pull requests merged in 2022-04, with the labels that each got.

#2656 displayElectionRound without `round`
  packages/ui/src/app/pages/Election/Election.tsx
  packages/ui/test/council/pages/Election.test.tsx
Labels: community-dev

#2767 MyStakeStat: String Concatenation in getTotalStake
  packages/ui/src/working-groups/components/MyStakeStat.tsx
Labels: community-dev

#2853 Proposal: Slash WG Lead needs to show current stake by lead
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SlashWorkingGroupLead.tsx
Labels: community-dev

#2904 Tech Debt: Use react syntax for SVG properties.
  packages/ui/src/common/components/page/MobileView/images/BuildLogo.tsx
  packages/ui/src/working-groups/components/WorkingGroupImage.tsx
Labels: jsg-code-review, builders-wg-code-review

#2903 2394 - Show correct stake required for the WG Opening
  packages/ui/src/working-groups/components/OpeningFormPreview.tsx
  packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.tsx
Labels: jsg-code-review, builders-wg-code-review

#2894 Bugfix/2838
  packages/ui/src/proposals/modals/VoteForProposal/components/SuccessModal.tsx
  packages/ui/test/proposals/modals/VoteForProposalModal.test.tsx
Labels: jsg-code-review

#2902 2419 - Pass placeholder as props for SelectWorkingGroupOpening.
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/CancelWorkingGroupLeadOpening.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/FillWorkingGroupLeadOpening.tsx
  packages/ui/src/working-groups/components/SelectWorkingGroupApplication/SelectWorkingGroupApplication.tsx
  packages/ui/src/working-groups/components/SelectWorkingGroupOpening/SelectWorkingGroupOpening.tsx
Labels: jsg-code-review, builders-wg-code-review
