Repository Joystream/pioneer, pull requests merged in 2022-09, with the labels that each got.

#3597 🦺 Improvement for forum actions with invitation lock
  packages/ui/src/bounty/modals/AuthorizeTransactionModal/AuthorizeTransactionModal.tsx
  packages/ui/src/forum/components/PostList/PostEditor.tsx
  packages/ui/src/forum/components/PostList/PostList.tsx
  packages/ui/src/forum/components/PostList/PostListItem.tsx
  packages/ui/src/forum/modals/CreateThreadModal/CreateThreadModal.tsx
  packages/ui/src/forum/modals/CreateThreadModal/CreateThreadSignModal.tsx
  packages/ui/src/forum/modals/PostActionModal/CreatePostModal/CreatePostModal.tsx
  packages/ui/src/forum/modals/PostActionModal/CreatePostModal/CreatePostSignModal.tsx
  packages/ui/src/forum/modals/PostActionModal/EditPostModal/EditPostModal.tsx
  packages/ui/src/forum/modals/PostActionModal/EditPostModal/index.ts
  packages/ui/src/forum/modals/PostActionModal/PostActionSignModal.tsx
Labels: waiting-for-checks

#3595 changed quorum bar with council's size
  packages/ui/src/proposals/components/StatisticsPreview/ProposalStatistics.stories.tsx
  packages/ui/src/proposals/components/StatisticsPreview/ProposalStatistics.tsx
Labels: community-dev, jsg-code-review

#3605 🌍 Bringing Update member modal to GlobalModals
  packages/ui/src/app/GlobalModals.tsx
  packages/ui/src/memberships/components/EditMembershipButton.tsx
  packages/ui/src/memberships/modals/UpdateMembershipModal/UpdateMembershipModal.tsx
  packages/ui/src/memberships/modals/UpdateMembershipModal/index.tsx
  packages/ui/test/membership/modals/UpdateMembershipModal.test.tsx
Labels: waiting-for-checks

#3599 🌍 Captcha on onboarding
  packages/ui/package.json
  packages/ui/src/common/modals/OnBoardingModal/OnBoardingModal.tsx
  packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
  packages/ui/test/membership/modals/BuyMembershipModal.test.tsx
  yarn.lock
Labels: waiting-for-checks

#3611 🧯 Quick fix on onboarding validation without captcha
  packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx
Labels: waiting-for-checks

#3562 🏛️ Implement new forum category page design
  packages/ui/src/app/components/PageLayout.tsx
  packages/ui/src/app/pages/Forum/ForumCategory.tsx
  packages/ui/src/common/components/CountBadge.tsx
  packages/ui/src/common/components/icons/RepliesIcon.tsx
  packages/ui/src/common/components/icons/index.ts
  packages/ui/src/common/constants/styles.ts
  packages/ui/src/forum/components/CardItem.tsx
  packages/ui/src/forum/components/ForumPageHeader.tsx
  packages/ui/src/forum/components/PostList/PostListItem.tsx
  packages/ui/src/forum/components/SuggestedThreads.tsx
  packages/ui/src/forum/components/category/CategoryListItem.stories.tsx
  packages/ui/src/forum/components/category/CategoryListItem.tsx
  packages/ui/src/forum/components/category/ForumCategoryList.tsx
  packages/ui/src/forum/components/category/LatestPost.tsx
  packages/ui/src/forum/components/category/PopularThread.tsx
  packages/ui/src/forum/components/category/ThreadCount.tsx
  packages/ui/src/forum/components/threads/ThreadBrowser.tsx
  packages/ui/src/forum/components/threads/ThreadItem.stories.tsx
  packages/ui/src/forum/components/threads/ThreadItem.tsx
Labels: community-dev, jsg-code-review

#3630 🙈 fix: Delete and Edit buttons are shown on removed thread pages #3266
  packages/ui/src/common/components/page/PageTitle.tsx
  packages/ui/src/forum/components/Thread/ThreadTitle.tsx
Labels: community-dev, jsg-code-review

#3634 Updated text "Blog Posts" to "Forum Posts"
  packages/ui/src/memberships/components/MemberProfile/MemberDetails.tsx
Labels: community-dev

#3614 🏴 Removing black loading modal
  packages/ui/src/app/GlobalModals.tsx
  packages/ui/src/app/pages/Bounty/components/BountiesLayout.tsx
  packages/ui/src/app/pages/WorkingGroups/WorkingGroups.tsx
  packages/ui/src/bounty/components/BountyActorsList/BountyActorsList.tsx
  packages/ui/src/bounty/components/BountyDiscussion/BountyDiscussion.tsx
  packages/ui/src/bounty/components/WithdrawInfo/WithdrawInfo.tsx
  packages/ui/src/bounty/modals/AddBountyModal/AddBountyModal.tsx
  packages/ui/src/bounty/modals/AnnounceWorkEntryModal/AnnounceWorkEntryModal.tsx
  packages/ui/src/bounty/modals/ClaimRewardModal/ClaimRewardModal.tsx
  packages/ui/src/bounty/modals/ContributeFundsModal/ContributeFundsModal.tsx
  packages/ui/src/bounty/modals/SubmitJudgementModal/SubmitJudgementModal.tsx
  packages/ui/src/bounty/modals/SubmitWorkModal/SubmitWorkModal.tsx
  packages/ui/src/bounty/modals/WithdrawContributionModal/WithdrawContributionModal.tsx
  packages/ui/src/bounty/modals/WithdrawWorkEntryModal/WithdrawWorkEntryModal.tsx
  packages/ui/src/bounty/modals/WithdrawalStakeModal/WithdrawStakeModal.tsx
  packages/ui/src/common/components/Loading.tsx
  packages/ui/src/common/components/Mention/ApplicationTooltip.tsx
  packages/ui/src/common/components/Mention/ForumPostTooltip.tsx
  packages/ui/src/common/components/Mention/ForumThreadTooltip.tsx
  packages/ui/src/common/components/Mention/Mention.tsx
  packages/ui/src/common/components/Mention/OpeningTooltip.tsx
  packages/ui/src/common/components/Mention/ProposalTooltip.tsx
  packages/ui/src/common/components/Mention/PrposalDiscussionEntryTooltip.tsx
  packages/ui/src/common/components/WaitModal.tsx
  packages/ui/src/common/components/icons/Loader.tsx
  packages/ui/src/common/components/page/SearchProcess.stories.tsx
  packages/ui/src/common/components/page/SearchProcess.tsx
  packages/ui/src/council/components/election/CandidateCard/CandidateCardList.tsx
  packages/ui/src/council/components/pastCouncil/PastCouncilsList/PastCouncilListItem.tsx
  packages/ui/src/forum/components/PostList/PostList.tsx
  packages/ui/src/forum/components/threads/ThreadListItem.tsx
  packages/ui/src/forum/modals/DeleteThreadModal/DeleteThreadModal.tsx
  packages/ui/src/forum/modals/PostActionModal/CreatePostModal/CreatePostModal.tsx
  packages/ui/src/forum/modals/PostActionModal/DeletePostModal/DeletePostModal.tsx
  packages/ui/src/forum/modals/PostActionModal/EditPostModal/EditPostModal.tsx
  packages/ui/src/memberships/modals/InviteMemberModal/InviteMemberModal.tsx
  packages/ui/src/memberships/modals/TransferInviteModal/TransferInviteModal.tsx
  packages/ui/src/overview/components/ProposalsOverview/ProposalTile.tsx
  packages/ui/src/proposals/components/ProposalList/ProposalItemVoteDetails.tsx
  packages/ui/src/proposals/components/ProposalList/ProposalList.tsx
  packages/ui/src/working-groups/modals/ApplicationDetailsModal/FormDetails.tsx
  packages/ui/test/app/pages/ProposalPreview.test.tsx
  packages/ui/test/app/pages/UpcomingOpening.test.tsx
  packages/ui/test/app/pages/WorkingGroup.test.tsx
  packages/ui/test/common/components/Mention.test.tsx
  packages/ui/test/council/pages/Council.test.tsx
  packages/ui/test/council/pages/Election.test.tsx
  packages/ui/test/council/pages/PastCouncil.test.tsx
  packages/ui/test/council/pages/PastCouncils.test.tsx
  packages/ui/test/council/pages/PastElection.test.tsx
  packages/ui/test/forum/pages/ForumThread.test.tsx
  packages/ui/test/membership/components/MyMemberships.test.tsx
  packages/ui/test/overview/components/CouncilOverview.test.tsx
  packages/ui/test/overview/components/ProposalsOverview.test.tsx
  packages/ui/test/overview/components/WorkingGroupsOverview.test.tsx
  packages/ui/test/proposals/components/ProposalListItem.test.tsx
  packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
  packages/ui/test/setup.ts
  packages/ui/test/working-groups/pages/MyApplications.test.tsx
  packages/ui/test/working-groups/pages/MyRoles.test.tsx
Labels: waiting-for-checks
