Repository Joystream/pioneer, pull requests merged in 2022-05, with the labels that each got.

#2699 Council announcement wording
  packages/ui/src/council/components/Activities/NewCouncilElectedContent.tsx
Labels: community-dev, jsg-code-review

#2961 2821: Create WG opening isn't clear enough on what leave_unstaking_period does
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/CreateWorkingGroupLeadOpening/StakingPolicyAndReward.tsx
Labels: jsg-code-review, builders-wg-code-review

#3003 ⏲️ Fix the Proposal "Time left" counter
  packages/ui/src/council/queries/__generated__/council.generated.tsx
  packages/ui/src/proposals/hooks/useBlocksToProposalExecution.ts
  packages/ui/src/proposals/queries/__generated__/proposals.generated.tsx
  packages/ui/src/proposals/queries/proposals.graphql
  packages/ui/src/proposals/types/ProposalWithDetails.ts
  packages/ui/src/proposals/types/proposals.ts
  packages/ui/test/common/components/Mention.test.tsx
Labels: hot-fix

#2981 fix/2864-Next button is outside of the screen when pasting large text
  packages/ui/src/forum/modals/CreateThreadModal/CreateThreadDetailsModal.tsx
Labels: community-dev, jsg-code-review

#2958 Fix Vertical scroller on empty screen
  packages/ui/src/app/components/OnboardingOverlay/OnBoardingOverlay.tsx
Labels: community-dev, builders-wg-code-review

#3037 fix/2423 Keep editable check button is not noticeable in Forum
  packages/ui/src/forum/components/Thread/NewThreadPost.tsx
  packages/ui/test/forum/components/NewThreadPost.test.tsx
Labels: community-dev, jsg-code-review, builders-wg-code-review

#3057 🧨 Hotfix on AddBountyModal validation mode
  packages/ui/src/bounty/modals/AddBountyModal/AddBountyModal.tsx
  packages/ui/test/bounty/modals/AddBountyModal.test.tsx
Labels: hot-fix

#3059 fix/2349-Bounty entrant minimum validation message
  packages/ui/src/bounty/modals/AddBountyModal/helpers.ts
Labels: community-dev, jsg-code-review

#3077 fix/2647 council title overflow on guest mode
  packages/ui/src/overview/components/CouncilOverview/CouncilTile.tsx
Labels: community-dev, jsg-code-review

#3061 fix/2509-submit-work-modal-small-copy-update
  packages/ui/src/bounty/modals/SubmitWorkModal/SubmitWorkModal.tsx
  packages/ui/src/services/i18n/dict/en/bounty.json
  packages/ui/src/services/i18n/dict/ru/bounty.json
Labels: community-dev, jsg-code-review

#3034 fix/2735-Better CTA for picking membershp on the forum
  packages/ui/src/forum/components/PostList/PostListItem.tsx
Labels: community-dev, jsg-code-review, builders-wg-code-review

#3103 Fix/2637 cancelling bounty
  packages/ui/src/bounty/modals/CancelBountyModal/components/AuthorizationModal.tsx
  packages/ui/src/bounty/modals/CancelBountyModal/components/SuccessModal.tsx
  packages/ui/src/services/i18n/dict/en/bounty.json
  packages/ui/src/services/i18n/dict/ru/bounty.json
Labels: jsg-code-review

#3060 2294 Sorting of proposals
  packages/ui/src/app/pages/Proposals/PastProposals.tsx
  packages/ui/src/app/pages/Proposals/Proposals.tsx
  packages/ui/src/proposals/components/ProposalList/ProposalList.tsx
  packages/ui/src/proposals/components/ProposalList/ProposalListItem.tsx
  packages/ui/src/proposals/constants/styles.ts
  packages/ui/src/proposals/hooks/useProposals.ts
  packages/ui/src/proposals/queries/__generated__/proposals.generated.tsx
  packages/ui/src/proposals/queries/proposals.graphql
Labels: community-dev, jsg-code-review
