Repository Joystream/pioneer, pull requests merged in 2023-06, with the labels that each got.

#4401 🦑 Add a link to the Calamar block explorer
  packages/ui/src/app/components/SideBar.tsx
  packages/ui/src/common/components/icons/symbols/CalamarSymbol.tsx
  packages/ui/src/common/components/icons/symbols/index.ts
  packages/ui/src/common/components/page/Sidebar/NavigationLink.tsx
Labels: builders-wg-code-review

#4383 🗝️ Fix `opening:create` on the liberated chain
  docs/mocks.md
  packages/ui/dev/node-mocks/commands/council/announce.ts
  packages/ui/dev/node-mocks/commands/council/elect.ts
  packages/ui/dev/node-mocks/commands/members/create.ts
  packages/ui/dev/node-mocks/commands/opening/create.ts
  packages/ui/dev/node-mocks/commands/proposals/approve.ts
  packages/ui/dev/node-mocks/commands/proposals/create.ts
  packages/ui/dev/node-mocks/commands/setLead.ts
  packages/ui/dev/node-mocks/lib/api.ts
  packages/ui/package.json
  packages/ui/src/proposals/hooks/useProposalConstants.ts
  yarn.lock
Labels: builders-wg-code-review

#4368 🩹 Address some slow or inconsistent tests
  .eslintrc.json
  packages/ui/jest.config.js
  packages/ui/src/bounty/components/BountyFooter.tsx
  packages/ui/src/common/components/BlockTime/BlockTime.tsx
  packages/ui/src/common/model/formatters.ts
  packages/ui/src/forum/components/threads/ThreadItemBreadcrumbs.tsx
  packages/ui/src/forum/hooks/useForumMultiQueryCategoryBreadCrumbs.ts
  packages/ui/test/_helpers/mockUniqueQuery.ts
  packages/ui/test/common/model/formatters.test.ts
  packages/ui/test/council/modals/RestoreVotesModal.test.tsx
  packages/ui/test/forum/components/ThreadItemBreadcrumbs.test.tsx
  packages/ui/tsconfig.json
Labels: builders-wg-code-review, CI-passed

#4406 ⬆️ Upgrade to Storybook 7
  package.json
  packages/markdown-editor/package.json
  packages/ui/.eslintrc.js
  packages/ui/.storybook/main.js
  packages/ui/package.json
  packages/ui/src/common/components/page/SideNotification.stories.tsx
  packages/ui/src/common/components/selects/select.stories.tsx
  packages/ui/src/common/components/statistics/DurationStatistics.stories.tsx
  packages/ui/src/memberships/components/MemberListItem/MemberListItem.stories.tsx
  packages/ui/src/memberships/components/MemberListItem/MyMemberListItem.stories.tsx
  packages/ui/src/proposals/components/ProposalList/ProposalList.stories.tsx
  yarn.lock
Labels: builders-wg-code-review

#4415 ⬆️ Upgrade to TypeScript 5
  packages/markdown-editor/package.json
  packages/ui/package.json
  packages/ui/src/accounts/components/AccountItem/components/styles.ts
  packages/ui/src/accounts/types/balances.ts
  packages/ui/src/common/components/buttons/Toggle.tsx
  packages/ui/src/common/components/selects/MultiSelect.tsx
  packages/ui/src/common/components/selects/SimpleSelect.tsx
  packages/ui/src/common/components/statistics/BlockDurationStatistics.tsx
  packages/ui/src/common/utils.ts
  packages/ui/src/forum/modals/CreateThreadModal/CreateThreadModal.tsx
  packages/ui/src/forum/modals/CreateThreadModal/machine.ts
  packages/ui/src/overview/components/DeadlineList/ElectionListItem.tsx
  packages/ui/src/proposals/types/ProposalsActivities/casts.ts
  packages/ui/src/proxyApi/client/query.ts
  packages/ui/src/proxyApi/client/tx.ts
  yarn.lock
Labels: builders-wg-code-review

#4426 Show all applicants
  packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
  packages/ui/src/working-groups/components/ApplicantsList.tsx
Labels: community-dev, jsg-code-review

#4431 Fix/close confirm modal
  packages/ui/src/common/providers/modal/provider.tsx
Labels: community-dev, jsg-code-review

#4408 Rename MoveFoundsModal to MoveFundsModal
  packages/ui/src/accounts/hooks/useHasRequiredStake.ts
  packages/ui/src/accounts/modals/MoveFundsModal/MoveFundsModal.tsx
  packages/ui/src/accounts/modals/MoveFundsModal/MoveFundsModalButtons.tsx
  packages/ui/src/accounts/modals/MoveFundsModal/MoveFundsModalInfo.tsx
  packages/ui/src/accounts/modals/MoveFundsModal/index.ts
  packages/ui/src/accounts/modals/MoveFundsModal/styles.ts
  packages/ui/src/accounts/modals/MoveFundsModal/types.ts
  packages/ui/src/app/GlobalModals.tsx
  packages/ui/src/bounty/modals/AnnounceWorkEntryModal/AnnounceWorkEntryModal.tsx
  packages/ui/src/council/modals/AnnounceCandidacy/AnnounceCandidacyModal.tsx
  packages/ui/src/council/modals/VoteForCouncil/VoteForCouncilModal.tsx
  packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
  packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.tsx
  packages/ui/test/council/modals/AnnounceCandidacyModal.test.tsx
  packages/ui/test/council/modals/VoteForCouncilModal.test.tsx
  packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
  packages/ui/test/working-groups/modals/ApplyForRoleModal.test.tsx
Labels: community-dev, jsg-code-review

#4446 🧪 POC Move the `ProposalPreview` tests to Storybook
  packages/ui/.storybook/main.js
  packages/ui/package.json
  packages/ui/src/app/pages/Proposals/ProposalPreview.stories.tsx
  packages/ui/src/app/pages/Proposals/ProposalPreview.tsx
  packages/ui/src/common/types/helpers.ts
  packages/ui/src/mocks/data/proposals.ts
  packages/ui/src/mocks/helpers/index.ts
  packages/ui/src/mocks/helpers/storybook.ts
  packages/ui/test/app/pages/ProposalPreview.test.tsx
  yarn.lock
Labels: builders-wg-code-review

#4442 fixes #4434: Hide total balance when wallet was disconected
  packages/ui/src/accounts/providers/balances/provider.tsx
Labels: community-dev

#4457 📚 Add modals support in stories
  packages/ui/.storybook/preview.tsx
  packages/ui/src/app/pages/Proposals/ProposalPreview.stories.tsx
  packages/ui/src/mocks/helpers/asChainData.ts
  packages/ui/src/mocks/helpers/index.ts
  packages/ui/src/mocks/helpers/transactions.ts
  packages/ui/src/mocks/providers/accounts.tsx
  packages/ui/src/mocks/providers/api.tsx
  packages/ui/src/mocks/providers/query-node.tsx
  packages/ui/test/_mocks/transactions.ts
Labels: builders-wg-code-review

#4458 🚚 Move the vote for proposal modal tests to Storybook
  packages/ui/.storybook/preview.tsx
  packages/ui/src/app/GlobalModals.tsx
  packages/ui/src/app/pages/Proposals/ProposalPreview.stories.tsx
  packages/ui/src/common/components/CKEditor/CKEditor.tsx
  packages/ui/src/common/components/forms/ToggleCheckbox.tsx
  packages/ui/src/mocks/helpers/storybook.ts
  packages/ui/src/mocks/providers/accounts.tsx
  packages/ui/src/proposals/modals/VoteForProposal/VoteForProposalModalForm.tsx
  packages/ui/test/proposals/modals/VoteForProposalModal.test.tsx
Labels: builders-wg-code-review

#4448 fix `MoveFoundsModal` (#4447)
  packages/ui/test/bounty/modals/AnnounceWorkEntryModal.test.tsx
Labels: community-dev, jsg-code-review
