Repository Joystream/pioneer, pull requests merged in 2023-11, with the labels that each got.

#4614 Fix the block link opening past elections
  packages/ui/src/common/components/BlockTime/BlockInfo.tsx
Labels: community-dev, jsg-code-review

#4364 🛰️ Backend deployments
  backend.Dockerfile
  backend.dev.Dockerfile
  packages/server/.env.dev
  packages/server/README.md
  packages/server/docker-compose.yml
  packages/server/docker/dev/entrypoint.sh
  packages/server/docker/dev/env.sh
  packages/server/docker/dev/notify.sh
  packages/server/docker/dev/prisma-deploy.sh
  packages/server/docker/prod/entrypoint.sh
  packages/server/docker/prod/notify.sh
  packages/server/docker/up.sh
  packages/server/package.json
  packages/server/src/common/config.ts
  packages/server/src/common/email-templates/pioneer-email.tsx
  packages/server/src/common/scripts/startApi.ts
  packages/server/src/common/utils/email.ts
  packages/server/src/notifier/processNotifications.ts
  packages/server/src/notifier/scripts/notifyNodeCron.ts
  render.yaml
  yarn.lock
Labels: scope:notifications, builders-wg-code-review, backend

#4622 🩹 Fix the `dev:authtoken` script
  packages/server/README.md
  packages/server/package.json
  packages/server/src/auth/model/token.ts
  packages/server/src/auth/scripts/generateToken.ts
Labels: scope:notifications, backend

#4608 📜 Log email activity
  packages/server/src/auth/model/emailVerification.ts
  packages/server/src/common/utils/email.ts
Labels: scope:notifications, backend

#4623 Rwd/address QA issue #4609
  packages/ui/src/app/components/SideBar.tsx
  packages/ui/src/app/pages/Proposals/ProposalPreview.tsx
  packages/ui/src/app/pages/Proposals/Proposals.tsx
  packages/ui/src/app/pages/Settings/Settings.tsx
  packages/ui/src/common/components/Activities/ActivityComponent.tsx
  packages/ui/src/common/components/page/PageContent.tsx
  packages/ui/src/common/components/page/SidePanel.tsx
  packages/ui/src/common/components/statistics/StatisticBar.tsx
  packages/ui/src/working-groups/components/WorkingGroupsList.tsx
Labels: qa-task, community-dev

#4625 Freeze pallet proposal creation
  packages/ui/package.json
  packages/ui/src/app/pages/Proposals/CurrentProposals.stories.tsx
  packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
  packages/ui/src/common/api/schemas/schema.graphql
  packages/ui/src/common/components/forms/InputComponent.tsx
  packages/ui/src/council/queries/__generated__/council.generated.tsx
  packages/ui/src/mocks/data/common.ts
  packages/ui/src/mocks/data/proposals.ts
  packages/ui/src/mocks/helpers/asChainData.ts
  packages/ui/src/mocks/helpers/proposalDetailsToConstantKey.ts
  packages/ui/src/proposals/hooks/useProposalConstants.ts
  packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SpecificParametersStep.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/UpdatePalletFrozenStatus.tsx
  packages/ui/src/proposals/modals/AddNewProposal/getSpecificParameters.ts
  packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
  packages/ui/src/proposals/modals/AddNewProposal/machine.ts
  packages/ui/src/proposals/model/proposalDescriptions.ts
  packages/ui/src/proposals/model/proposalDetails.ts
  packages/ui/src/proposals/model/validation.ts
  packages/ui/src/proposals/queries/__generated__/proposals.generated.tsx
  packages/ui/src/proposals/queries/proposals.graphql
  packages/ui/src/proposals/types/proposals.ts
  yarn.lock
Labels: community-dev, jsg-code-review, nara-network

#4627 Preview freeze pallet proposal
  packages/ui/src/app/pages/Proposals/ProposalPreview.stories.tsx
  packages/ui/src/proposals/helpers/getDetailsRenderStructure.ts
  packages/ui/src/proposals/types/ProposalDetails.ts
Labels: community-dev, jsg-code-review, nara-network

#4632 Create freeze pallet proposal design followup
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/UpdatePalletFrozenStatus.tsx
Labels: community-dev, nara-network

#4554 Fix past councils spending amounts
  packages/ui/src/council/hooks/usePastCouncil.ts
  packages/ui/src/council/hooks/usePastCouncilStats.ts
  packages/ui/src/council/queries/__generated__/council.generated.tsx
  packages/ui/src/council/queries/council.graphql
  packages/ui/src/council/types/PastCouncil.ts
  packages/ui/test/council/pages/PastCouncil.test.tsx
Labels: community-dev, jsg-code-review

#4450 Fix/4379 member acount balance
  packages/ui/src/memberships/components/MemberProfile/MemberAccount.tsx
  packages/ui/src/memberships/components/MemberProfile/MemberAccounts.tsx
Labels: community-dev, jsg-code-review

#4624 Backend Docker GitHub workflow
  .github/workflows/backend-docker.yml
  backend.Dockerfile
  backend.dev.Dockerfile
  packages/server/README.md
  packages/server/docker-compose.yml
  packages/server/docker/compose.network.yml
  packages/server/docker/up.sh
  packages/server/docker/yarn.lock
  packages/server/docker/yarn.sh
  packages/server/package.json
  render.yaml
  yarn.lock
Labels: backend
