Repository Joystream/pioneer, pull requests merged in 2023-07, with the labels that each got.

#4464 🕹️ Fix controls in App stories
  packages/ui/src/app/App.stories.tsx
Labels: builders-wg-code-review

#4465 📖 Add stories for the current and past proposals pages
  packages/ui/.storybook/preview.tsx
  packages/ui/src/app/pages/Proposals/CurrentProposals.stories.tsx
  packages/ui/src/app/pages/Proposals/PastProposals.stories.tsx
  packages/ui/src/app/pages/Proposals/ProposalPreview.stories.tsx
  packages/ui/src/common/types/helpers.ts
  packages/ui/src/mocks/data/proposals.ts
  packages/ui/src/mocks/providers/api.tsx
  packages/ui/src/mocks/providers/index.tsx
  packages/ui/src/mocks/providers/query-node.tsx
  packages/ui/src/mocks/providers/router.tsx
  packages/ui/src/proposals/components/ProposalFilters/ProposalFilters.stories.tsx
  packages/ui/src/proposals/components/ProposalList/ProposalList.stories.tsx
  packages/ui/src/proposals/components/ProposalList/ProposalListItem.stories.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/ProposalTypeStep.stories.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/RationaleModal.stories.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/DecreaseWorkingGroupLeadStake.stories.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/RuntimeUpgrade.stories.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SetCouncilBudgetIncrement.stories.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SetMembershipLeadInvitationQuota.stories.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/SetReferralCut.stories.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/UpdateChannelPayouts/UpdateChannelPayouts.stories.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/CancelWorkingGroupLeadOpening.stories.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/CreateWorkingGroupLeadOpening/CreateWorkingGroupLeadOpening.stories.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/FillWorkingGroupLeadOpening.stories.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SuccessModal.stories.tsx
Labels: builders-wg-code-review

#4473 🤯 Refactor add new proposal tests
  packages/ui/.storybook/preview.tsx
  packages/ui/src/app/pages/Proposals/CurrentProposals.stories.tsx
  packages/ui/src/app/pages/Proposals/PastProposals.stories.tsx
  packages/ui/src/app/pages/Proposals/ProposalPreview.stories.tsx
  packages/ui/src/common/components/forms/InputNumber.tsx
  packages/ui/src/common/utils/validation.tsx
  packages/ui/src/mocks/data/members.ts
  packages/ui/src/mocks/data/proposals.ts
  packages/ui/src/mocks/helpers/storybook.ts
  packages/ui/src/mocks/providers/api.tsx
  packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/WarningModal.tsx
  packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
  packages/ui/src/proposals/queries/index.ts
  packages/ui/test/council/modals/AnnounceCandidacyModal.test.tsx
  packages/ui/test/proposals/modals/AddNewProposalModal.test.tsx
Labels: builders-wg-code-review

#4375 4326-Validators list - Page and widgets
  packages/ui/src/app/pages/Validators/ValidatorList.stories.tsx
  packages/ui/src/app/pages/Validators/ValidatorList.tsx
  packages/ui/src/common/components/charts/PercentageChart.tsx
  packages/ui/src/common/components/statistics/StatisticHeader.tsx
  packages/ui/src/common/components/statistics/Statistics.tsx
  packages/ui/src/common/components/typography/TokenValue.tsx
  packages/ui/src/common/constants/numbers.ts
  packages/ui/src/mocks/helpers/asChainData.ts
  packages/ui/src/validators/components/statistics/Era.tsx
  packages/ui/src/validators/components/statistics/Rewards.tsx
  packages/ui/src/validators/components/statistics/Staking.tsx
  packages/ui/src/validators/components/statistics/ValidatorsState.tsx
  packages/ui/src/validators/hooks/useStakingStatistics.tsx
Labels: community-dev

#4483 fix member handle issue from forum
  packages/ui/src/common/components/Mention/Mention.tsx
Labels: jsg-code-review
