Repository Joystream/pioneer, pull requests merged in 2023-10, with the labels that each got.

#4461 Create an opening #306 fix
  packages/ui/src/app/GlobalModals.tsx
  packages/ui/src/app/pages/WorkingGroups/WorkingGroup/WorkingGroup.stories.tsx
  packages/ui/src/app/pages/WorkingGroups/WorkingGroup/WorkingGroup.tsx
  packages/ui/src/common/components/buttons/DownloadButtons.tsx
  packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/CreateWorkingGroupLeadOpening/ApplicationForm.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/CreateWorkingGroupLeadOpening/DurationAndProcess.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/CreateWorkingGroupLeadOpening/StakingPolicyAndReward.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/CreateWorkingGroupLeadOpening/WorkingGroupAndDescription.tsx
  packages/ui/src/working-groups/components/CreateOpening/ApplicationForm.tsx
  packages/ui/src/working-groups/components/CreateOpening/DurationAndProcess.tsx
  packages/ui/src/working-groups/components/CreateOpening/StakingPolicyAndReward.tsx
  packages/ui/src/working-groups/components/CreateOpening/WorkingGroupAndDescription.tsx
  packages/ui/src/working-groups/components/CreateOpeningButton.tsx
  packages/ui/src/working-groups/modals/CreateOpening/CreateOpening.tsx
  packages/ui/src/working-groups/modals/CreateOpening/components/Import.tsx
  packages/ui/src/working-groups/modals/CreateOpening/components/Steps.tsx
  packages/ui/src/working-groups/modals/CreateOpening/components/Success.tsx
  packages/ui/src/working-groups/modals/CreateOpening/components/index.ts
  packages/ui/src/working-groups/modals/CreateOpening/index.ts
  packages/ui/src/working-groups/modals/CreateOpening/machine.ts
  packages/ui/src/working-groups/modals/CreateOpening/types.tsx
  packages/ui/src/working-groups/modals/CreateOpening/utils.ts
Labels: community-dev, jsg-code-review

#4536 Allow for custom query node to be used
  packages/ui/src/app/config/network.ts
  packages/ui/src/app/pages/Settings/Settings.tsx
  packages/ui/src/common/components/SettingsInformation.tsx
  packages/ui/src/common/hooks/useNetwork.ts
  packages/ui/src/common/providers/network-endpoints/provider.tsx
  packages/ui/src/services/i18n/dict/en/settings.json
Labels: community-dev, jsg-code-review

#4551 integrate basic notifications signup
  packages/server/src/auth/model/emailVerification.ts
  packages/server/test/api/utils.ts
  packages/ui/.storybook/main.js
  packages/ui/src/app/App.stories.tsx
  packages/ui/src/app/GlobalModals.tsx
  packages/ui/src/app/config/network.ts
  packages/ui/src/app/pages/Proposals/CurrentProposals.stories.tsx
  packages/ui/src/app/pages/Proposals/PastProposals.stories.tsx
  packages/ui/src/app/pages/Proposals/ProposalPreview.stories.tsx
  packages/ui/src/app/providers/backend/context.ts
  packages/ui/src/app/providers/backend/provider.tsx
  packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
  packages/ui/src/common/api/schemas/backendSchema.graphql
  packages/ui/src/common/hooks/useBackend.ts
  packages/ui/src/common/providers/network-endpoints/provider.tsx
  packages/ui/src/memberships/components/CurrentMember/CurrentMember.tsx
  packages/ui/src/memberships/constants/email.ts
  packages/ui/src/memberships/constants/index.ts
  packages/ui/src/memberships/hooks/useNotificationSettings.ts
  packages/ui/src/memberships/modals/EmailConfirmationModal/EmailConfirmationModal.tsx
  packages/ui/src/memberships/modals/EmailConfirmationModal/index.ts
  packages/ui/src/memberships/modals/EmailSubscriptionModal/EmaiSubscriptionFormModal.tsx
  packages/ui/src/memberships/modals/EmailSubscriptionModal/EmailSubscriptionModal.tsx
  packages/ui/src/memberships/modals/EmailSubscriptionModal/machine.ts
  packages/ui/src/memberships/model/backendAuth.ts
  packages/ui/src/memberships/queries/__generated__/backend.generated.tsx
  packages/ui/src/memberships/queries/backend.graphql
  packages/ui/src/mocks/providers/accounts.tsx
  packages/ui/src/mocks/providers/backend.tsx
  packages/ui/src/mocks/providers/gql.tsx
  packages/ui/src/mocks/providers/index.tsx
  packages/ui/src/mocks/providers/query-node.tsx
  packages/ui/src/mocks/providers/router.tsx
  packages/ui/test/_mocks/providers.tsx
  packages/ui/test/membership/components/CurrentMember.test.tsx
Labels: scope:notifications, community-dev

#4561 [backend] update schema
  packages/server/prisma/migrations/20231004111039_init/migration.sql
  packages/server/prisma/schema.prisma
  packages/server/src/auth/api/auth.ts
  packages/server/src/auth/api/member.ts
  packages/server/src/notifier/api/notification.ts
  packages/server/src/notifier/createNotifications.ts
  packages/server/src/notifier/model/notifications.ts
  packages/server/src/notifier/processNotifications.ts
  packages/server/src/notifier/scripts/mockEmail.ts
  packages/server/test/_mocks/notifier/createMember.ts
  packages/server/test/api/auth.test.ts
  packages/server/test/api/notifier.test.ts
  packages/server/test/notifier.test.ts
Labels: scope:notifications, community-dev, backend

#4523 Reduce `ForumPost` requests on category pages
  packages/ui/src/forum/hooks/useCategoryLatestPost.ts
  packages/ui/src/forum/hooks/useForumCategoryThreadCount.ts
  packages/ui/src/forum/hooks/useForumPopularThreads.ts
  packages/ui/src/forum/hooks/useThreadLatestPost.ts
Labels: community-dev, jsg-code-review

#4567 Rwd/sidebar and council
  packages/ui/src/app/App.tsx
  packages/ui/src/app/Providers.tsx
  packages/ui/src/app/components/NavBar.tsx
  packages/ui/src/app/components/OnboardingOverlay/OnBoardingOverlay.tsx
  packages/ui/src/app/components/PageLayout.tsx
  packages/ui/src/app/components/SideBar.tsx
  packages/ui/src/app/components/SideBarSlider.tsx
  packages/ui/src/app/pages/Council/PastCouncils/PastCouncil.tsx
  packages/ui/src/common/components/BadgeStatus/BadgesRow.ts
  packages/ui/src/common/components/BlockTime/BlockTime.tsx
  packages/ui/src/common/components/EmptyPagePlaceholder/EmptyPagePlaceholder.tsx
  packages/ui/src/common/components/icons/MenuIcon.tsx
  packages/ui/src/common/components/icons/index.ts
  packages/ui/src/common/components/page/MobileView/MobileView.stories.tsx
  packages/ui/src/common/components/page/MobileView/MobileView.tsx
  packages/ui/src/common/components/page/MobileView/images/BuildLogo.tsx
  packages/ui/src/common/components/page/Page.tsx
  packages/ui/src/common/components/page/SidePanel.tsx
  packages/ui/src/common/components/page/Sidebar/Navigation.tsx
  packages/ui/src/common/hooks/useResponsive.ts
  packages/ui/src/common/providers/responsive/context.ts
  packages/ui/src/common/providers/responsive/provider.tsx
  packages/ui/src/council/components/councilList/CouncilList.tsx
  packages/ui/src/council/components/councilList/CouncilListItem.tsx
  packages/ui/src/council/components/pastCouncil/PastCouncilMembers/PastCouncilMembers.tsx
  packages/ui/src/council/components/pastCouncil/PastCouncilProposals/PastCouncilProposals.tsx
  packages/ui/src/council/components/pastCouncil/PastCouncilWorkingGroups/PastCouncilWorkingGroups.tsx
  packages/ui/src/council/components/pastCouncil/PastCouncilsList/PastCouncilsList.tsx
  packages/ui/src/index.tsx
Labels: community-dev, jsg-code-review

#4563 add notifications settings tab
  packages/server/.env.dev
  packages/server/src/auth/api/member.ts
  packages/server/src/common/config.ts
  packages/server/src/common/utils/email.ts
  packages/ui/src/app/App.tsx
  packages/ui/src/app/components/SideBar.tsx
  packages/ui/src/app/constants/routes.ts
  packages/ui/src/app/hooks/usePageTabs.ts
  packages/ui/src/app/pages/Settings/Settings.tsx
  packages/ui/src/app/pages/Settings/SettingsLayout.tsx
  packages/ui/src/app/pages/Settings/SettingsModule.tsx
  packages/ui/src/app/pages/Settings/SettingsNetworkTab.tsx
  packages/ui/src/app/pages/Settings/SettingsNotificationsTab.stories.tsx
  packages/ui/src/app/pages/Settings/SettingsNotificationsTab.tsx
  packages/ui/src/app/pages/Settings/routes.ts
  packages/ui/src/app/providers/backend/provider.tsx
  packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
  packages/ui/src/common/api/schemas/backendSchema.graphql
  packages/ui/src/common/components/Warning.stories.tsx
  packages/ui/src/common/components/Warning.tsx
  packages/ui/src/common/components/icons/symbols/InfoSymbol.tsx
  packages/ui/src/common/components/icons/symbols/index.ts
  packages/ui/src/memberships/components/CurrentMember/CurrentMember.tsx
  packages/ui/src/memberships/hooks/useNotificationSettings.ts
  packages/ui/src/memberships/modals/DisconnectWalletModal/DisconnectWalletModal.tsx
  packages/ui/src/memberships/modals/EmailSubscriptionModal/EmailSubscriptionModal.tsx
  packages/ui/src/memberships/modals/EmailSubscriptionModal/index.tsx
  packages/ui/src/memberships/queries/__generated__/backend.generated.tsx
  packages/ui/src/memberships/queries/backend.graphql
  packages/ui/src/mocks/providers/backend.tsx
  packages/ui/src/mocks/providers/gql.tsx
  packages/ui/src/services/i18n/dict/en/settings.json
  packages/ui/test/app/pages/Settings.test.tsx
Labels: scope:notifications, community-dev

#4584 add support for backend re-authentication
  packages/server/src/auth/model/token.ts
  packages/ui/src/app/pages/Settings/SettingsNotificationsTab.stories.tsx
  packages/ui/src/app/pages/Settings/SettingsNotificationsTab.tsx
  packages/ui/src/app/providers/backend/provider.tsx
  packages/ui/src/memberships/queries/__generated__/backend.generated.tsx
  packages/ui/src/memberships/queries/backend.graphql
  packages/ui/src/mocks/providers/gql.tsx
Labels: scope:notifications, community-dev, jsg-code-review, backend

#4577 RWD/my profile and members
  packages/ui/src/accounts/components/Accounts.tsx
  packages/ui/src/app/GlobalModals.tsx
  packages/ui/src/app/components/SideBar.tsx
  packages/ui/src/app/components/SideBarSlider.tsx
  packages/ui/src/app/pages/Profile/MyMemberships.tsx
  packages/ui/src/common/components/Modal/Modal.tsx
  packages/ui/src/common/components/NotSupportMobileModal.tsx
  packages/ui/src/common/components/Pagination/Pagination.tsx
  packages/ui/src/common/components/statistics/Statistics.tsx
  packages/ui/src/common/providers/responsive/context.ts
  packages/ui/src/common/providers/responsive/provider.tsx
  packages/ui/src/memberships/components/MemberList/Members.tsx
  packages/ui/src/memberships/components/MemberListFilters/MemberListFilters.tsx
  packages/ui/src/memberships/components/MemberListItem/Fields.tsx
  packages/ui/src/memberships/components/MembersSection.tsx
  packages/ui/test/setup.ts
Labels: community-dev

#4411 ⬆️ Upgrade the project Node.js dependency
  package.json
Labels: backend

#4585 My Voting Result was wrong!
  packages/ui/src/council/components/election/pastElection/PastElectionTabs.tsx
Labels: community-dev, jsg-code-review

#4578 fix/past-election#4090
  packages/ui/src/app/pages/Election/PastElections/PastElections.tsx
  packages/ui/src/council/components/election/pastElection/PastElectionTabs.tsx
  packages/ui/src/council/components/election/pastElection/PastElectionsList/PastElectionsListRow.tsx
  packages/ui/src/council/queries/__generated__/council.generated.tsx
  packages/ui/src/council/queries/council.graphql
  packages/ui/src/council/types/PastElection.ts
Labels: qa-task, community-dev

#4258 Fix Election Blocktime Tooltip (#4156)
  packages/ui/src/common/components/BlockTime/BlockHistoryLine.stories.tsx
  packages/ui/src/common/components/BlockTime/BlockHistoryLine.tsx
  packages/ui/src/common/components/BlockTime/index.ts
  packages/ui/src/common/components/Stepper/Stepper.stories.tsx
  packages/ui/src/proposals/components/ProposalHistory.tsx
Labels: community-dev, jsg-code-review

#4590 Rwd/proposals and working groups
  packages/ui/.storybook/preview.tsx
  packages/ui/src/app/GlobalModals.tsx
  packages/ui/src/app/components/PageLayout.tsx
  packages/ui/src/app/pages/Council/PastCouncils/PastCouncil.tsx
  packages/ui/src/app/pages/Proposals/PastProposals.tsx
  packages/ui/src/app/pages/Proposals/ProposalPreview.tsx
  packages/ui/src/app/pages/Proposals/Proposals.tsx
  packages/ui/src/app/pages/WorkingGroups/MyRoles/MyRole.tsx
  packages/ui/src/app/pages/WorkingGroups/WorkingGroup/components/WorkersHistory.tsx
  packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpening.tsx
  packages/ui/src/common/components/BadgeStatus/BadgesRow.ts
  packages/ui/src/common/components/SidePane/SidePane.tsx
  packages/ui/src/common/components/StepperModal.tsx
  packages/ui/src/common/components/Tabs.tsx
  packages/ui/src/common/components/forms/DatePicker/DatePicker.tsx
  packages/ui/src/common/components/forms/FilterBox/FilterPageHeader.tsx
  packages/ui/src/common/components/forms/InputComponent.tsx
  packages/ui/src/common/components/page/PageContent.tsx
  packages/ui/src/common/components/page/PageTitle.tsx
  packages/ui/src/common/components/page/SideNotification.tsx
  packages/ui/src/common/components/statistics/StatisticBar.tsx
  packages/ui/src/council/modals/AnnounceCandidacy/AnnounceCandidacyModal.tsx
  packages/ui/src/forum/components/Thread/NewThreadPost.tsx
  packages/ui/src/proposals/components/AddProposalButton.tsx
  packages/ui/src/proposals/components/ProposalDetails/ProposalDetails.tsx
  packages/ui/src/proposals/components/ProposalFilters/ProposalFilters.tsx
  packages/ui/src/proposals/components/ProposalList/ProposalItemVoteDetails.tsx
  packages/ui/src/proposals/components/ProposalList/ProposalList.tsx
  packages/ui/src/proposals/components/ProposalList/ProposalListItem.tsx
  packages/ui/src/proposals/components/RationalePreview/RationalePreview.tsx
  packages/ui/src/proposals/components/StorybookTemplates.tsx
  packages/ui/src/proposals/constants/styles.ts
  packages/ui/src/proposals/modals/AddNewProposal/AddNewProposalModal.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/ProposalTypeStep.stories.tsx
  packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/DecreaseWorkingGroupLeadStake.stories.tsx
  packages/ui/src/working-groups/components/Applications/ApplicationsItems.tsx
  packages/ui/src/working-groups/components/ApplicationsList.tsx
  packages/ui/src/working-groups/components/OpeningsList/OpeningsList.tsx
  packages/ui/src/working-groups/components/Roles/MyRoleAccount.tsx
  packages/ui/src/working-groups/components/Roles/RolesList.tsx
  packages/ui/src/working-groups/components/WorkingGroupListItem.tsx
  packages/ui/src/working-groups/components/WorkingGroupsList.tsx
  packages/ui/test/proposals/components/ProposalListItem.test.tsx
Labels: community-dev, jsg-code-review

#4570 Fix/linkedin missing list
  packages/ui/package.json
  packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
  packages/ui/src/common/api/schemas/schema.graphql
  packages/ui/src/common/components/icons/socials/Linkedin.tsx
  packages/ui/src/common/components/icons/socials/index.ts
  packages/ui/src/memberships/components/MemberListFilters/MemberListFilters.tsx
  packages/ui/src/memberships/components/SocialMediaSelector.tsx
  packages/ui/src/memberships/components/SocialMediaSelector/SocialMediaSelector.tsx
  packages/ui/src/memberships/components/SocialMediaTile/SocialMediaTile.tsx
  yarn.lock
Labels: community-dev, jsg-code-review
