Repository Joystream/pioneer, pull requests merged in 2023-09, with the labels that each got.

#4511 [backend] add new email template
  packages/server/.env.dev
  packages/server/.gitignore
  packages/server/README.md
  packages/server/jest.config.ts
  packages/server/package.json
  packages/server/src/auth/api/auth.ts
  packages/server/src/common/config.ts
  packages/server/src/common/email-templates/README.md
  packages/server/src/common/email-templates/pioneer-email.tsx
  packages/server/src/common/utils/email.ts
  packages/server/src/notifier/model/email/forum.ts
  packages/server/src/notifier/model/email/index.ts
  packages/server/src/notifier/model/email/utils/forum.ts
  packages/server/src/notifier/model/email/utils/index.ts
  packages/server/src/notifier/model/event/forum.ts
  packages/server/src/notifier/scripts/mockEmail.ts
  packages/server/src/notifier/sendNotifications.ts
  packages/server/test/api/auth.test.ts
  packages/server/test/notifier.test.ts
  packages/server/test/setup.ts
  yarn.lock
Labels: backend

#4518 [backend] add election stage change notifications
  packages/server/prisma/migrations/20230903121816_election_events/migration.sql
  packages/server/prisma/schema.prisma
  packages/server/src/notifier/model/email/election.ts
  packages/server/src/notifier/model/email/index.ts
  packages/server/src/notifier/model/event/election.ts
  packages/server/src/notifier/model/event/index.ts
  packages/server/src/notifier/model/event/utils/types.ts
  packages/server/src/notifier/model/subscriptionKinds.ts
  packages/server/src/notifier/queries/events.graphql
  packages/server/test/_mocks/notifier/events/election.ts
  packages/server/test/notifier.test.ts
Labels: backend

#4522 [backend] add email send retries
  packages/server/README.md
  packages/server/prisma/migrations/20230904104915_notification_status/migration.sql
  packages/server/prisma/schema.prisma
  packages/server/src/common/config.ts
  packages/server/src/notifier/api/notification.ts
  packages/server/src/notifier/index.ts
  packages/server/src/notifier/processNotifications.ts
  packages/server/src/notifier/scripts/mockEmail.ts
  packages/server/src/notifier/sendNotifications.ts
  packages/server/test/api/auth.test.ts
  packages/server/test/api/notifier.test.ts
  packages/server/test/notifier.test.ts
  packages/server/test/setup.ts
Labels: backend

#4531 [backend] improve auth, add change email mutation
  packages/server/README.md
  packages/server/src/auth/api/auth.ts
  packages/server/src/auth/api/member.ts
  packages/server/src/auth/model/emailVerification.ts
  packages/server/src/auth/model/token.ts
  packages/server/src/common/api/context.ts
  packages/server/src/common/api/email.ts
  packages/server/src/notifier/api/entitySubscription.ts
  packages/server/src/notifier/api/generalSubscription.ts
  packages/server/src/notifier/api/notification.ts
  packages/server/test/api/auth.test.ts
  packages/server/test/api/notifier.test.ts
  packages/server/test/api/utils.ts
Labels: backend

#4513 Issue 4398 - How to buy $JOY
  packages/ui/src/app/pages/Profile/MyAccounts.tsx
  packages/ui/src/app/pages/Profile/components/BannerSection.tsx
  packages/ui/src/common/components/Tooltip/Tooltip.tsx
  packages/ui/src/memberships/components/ProfileComponent.tsx
Labels: community-dev, jsg-code-review

#4537 working group page story
  packages/ui/src/app/pages/WorkingGroups/WorkingGroup/WorkingGroup.stories.tsx
Labels: community-dev, jsg-code-review

#4530 Working groups opening story
  packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpenings.stories.tsx
Labels: community-dev, jsg-code-review

#4545 Fix-4504: fixed the css for indents
  packages/ui/src/common/components/MarkdownPreview/MarkdownPreviewStyles.tsx
Labels: community-dev, jsg-code-review

#4553 Fix-3225: used BudgetUpdatedEvent instead of BudgetSetEvent
  packages/ui/src/council/hooks/usePastCouncilWorkingGroups.ts
  packages/ui/src/council/queries/__generated__/council.generated.tsx
  packages/ui/src/council/queries/council.graphql
  packages/ui/src/council/types/PastCouncilWorkingGroup.ts
  packages/ui/src/mocks/server.ts
  packages/ui/test/council/pages/PastCouncil.test.tsx
Labels: community-dev, jsg-code-review

#4478 Added Proposal Grace Period
  packages/ui/src/app/pages/Proposals/ProposalPreview.stories.tsx
  packages/ui/src/app/pages/Proposals/ProposalPreview.tsx
  packages/ui/src/common/types/Block.ts
  packages/ui/src/mocks/helpers/randomBlock.ts
  packages/ui/src/proposals/components/ProposalDetails/ProposalDetails.tsx
  packages/ui/src/proposals/components/ProposalDetails/renderers/BlockTimeDisplay.tsx
  packages/ui/src/proposals/components/ProposalDetails/renderers/NumberOfBlocks.tsx
  packages/ui/src/proposals/helpers/getDetailsRenderStructure.ts
Labels: community-dev
