Repository Joystream/pioneer, pull requests merged in 2023-01, with the labels that each got.

#3995 🩹 Fix proposal view crashing due to high amounts of JOY
  packages/ui/src/proposals/types/ProposalDetails.ts
Labels: jsg-code-review

#3989 fix 2342
  packages/ui/src/app/pages/Settings/Settings.tsx
Labels: community-dev, jsg-code-review

#4027 Fix typo (#4025)
  packages/ui/src/working-groups/components/Activities/StakeSlashedContent.tsx
Labels: community-dev, jsg-code-review

#4023 update transaction at postText updated
  packages/ui/src/forum/modals/PostReplyModal/PostReplyModal.tsx
Labels: community-dev, hot-fix, jsg-code-review

#4049 Rename Proposal `Constants` to `Parameters` (#4046)
  packages/ui/src/proposals/modals/AddNewProposal/components/ProposalConstantsWrapper.tsx
Labels: community-dev, jsg-code-review

#4055 Fix typo and link on `StakeStep` (#4054)
  packages/ui/src/accounts/components/StakeStep.tsx
Labels: community-dev, jsg-code-review

#4070 Don't truncate Category description (#3904)
  packages/ui/src/app/pages/Forum/ForumCategory.tsx
Labels: community-dev, jsg-code-review

#4069 Fix candidacy staking and voting stake tooltips
  packages/ui/src/council/components/election/CandidateVote/CandidateVote.tsx
  packages/ui/src/council/modals/AnnounceCandidacy/components/StakeStep.tsx
Labels: community-dev, jsg-code-review, SP:1

#4064 ⬆️ Update QN schema
  .eslintrc.json
  package.json
  packages/ui/package.json
  packages/ui/src/common/api/queries/__generated__/baseTypes.generated.ts
  packages/ui/src/common/api/schemas/schema.graphql
  packages/ui/src/council/components/election/CandidateVote/CandidateVote.tsx
  packages/ui/src/council/queries/__generated__/council.generated.tsx
  packages/ui/src/council/queries/__generated__/councilEvents.generated.tsx
  packages/ui/src/forum/components/PostList/PostListItem.stories.tsx
  packages/ui/src/forum/components/threads/ThreadListItem.tsx
  packages/ui/src/forum/queries/__generated__/forumEvents.generated.tsx
  packages/ui/src/forum/types/ForumPost.ts
  packages/ui/src/memberships/queries/__generated__/members.generated.tsx
  packages/ui/src/memberships/types/casting.ts
  packages/ui/src/mocks/resolvers/baseResolvers.ts
  packages/ui/src/proposals/queries/__generated__/proposals.generated.tsx
  packages/ui/src/proposals/queries/__generated__/proposalsEvents.generated.tsx
  packages/ui/src/working-groups/queries/__generated__/workingGroupsEvents.generated.tsx
  packages/ui/src/working-groups/queries/workingGroupsEvents.graphql
  packages/ui/src/working-groups/types/WorkingGroupActivity/casts.ts
  packages/ui/test/council/components/ElectionVotes.test.tsx
  packages/ui/test/membership/modals/UpdateMembershipModal.test.tsx
  yarn.lock
Labels: ephesus
